const apiBaseUrl = (import.meta.env.VITE_API_BASE_URL || "http://localhost:8050").replace(/\/$/, "");

export interface BatchStep { id: string; step_code: string; step_name: string; step_order: number; step_type: string; description: string; enabled: boolean; expected_duration_ms: number; }
export interface BatchRunBrief { id: string; run_number: string; status: string; duration_ms: number | null; records_processed: number; records_failed: number; started_at: string; }
export interface BatchJob { id: string; job_code: string; name: string; description: string; job_type: string; module: string; business_service: string; application_name: string; enabled: boolean; default_severity: string; sla_minutes: number; step_count: number; steps: BatchStep[]; recent_runs: BatchRunBrief[]; created_at: string; updated_at: string; }
export interface BatchStepRun { id: string; job_step_id: string; step_code: string; step_name: string; step_order: number; status: string; started_at: string; completed_at: string | null; duration_ms: number | null; records_processed: number; records_succeeded: number; records_failed: number; failure_type: string | null; failure_message: string | null; technical_context: Record<string, unknown> | null; }
export interface BatchEvent { id: string; batch_run_id: string; event_type: string; from_status: string | null; to_status: string | null; message: string; event_payload: Record<string, unknown> | null; created_by: string; created_at: string; }
export interface BatchRun { id: string; run_number: string; job_id: string; job_code: string; job_name: string; status: string; trigger_type: string; scenario_code: string; started_at: string; completed_at: string | null; duration_ms: number | null; records_processed: number; records_succeeded: number; records_failed: number; failure_type: string | null; failure_message: string | null; summary: string; linked_exception_id: string | null; linked_exception_number: string | null; linked_ticket_id: string | null; linked_ticket_number: string | null; linked_alert_id: string | null; linked_diagnostic_case_id: string | null; linked_diagnostic_number: string | null; created_by: string; created_at: string; updated_at: string; steps: BatchStepRun[]; events: BatchEvent[]; }
export interface BatchSummary { batch_jobs: number; runs_total: number; runs_success: number; runs_failed: number; runs_partial: number; runs_timeout: number; open_batch_tickets: number; open_batch_exceptions: number; last_run_status: string | null; }
export interface BatchSimulationResult { run: BatchRun; exception_id: string | null; exception_number: string | null; ticket_id: string | null; ticket_number: string | null; diagnostic_case_id: string | null; diagnostic_number: string | null; }
export interface BatchSuiteResult { runs_created: number; successful_runs: number; failed_runs: number; partial_runs: number; tickets_created: number; exceptions_created: number; diagnostics_created: number; summary: string; results: BatchSimulationResult[]; }

async function request<T>(path: string, options: RequestInit = {}): Promise<T> { const response = await fetch(apiBaseUrl + path, { ...options, headers: { "Content-Type": "application/json", ...(options.headers || {}) } }); const body = await response.json().catch(() => ({})); if (!response.ok) throw new Error(`Batch API returned ${response.status}: ${typeof body === "object" && body?.detail ? body.detail : "request failed"}`); return body as T; }
export const getBatchSummary = () => request<BatchSummary>("/api/v1/batch/summary");
export const getBatchJobs = () => request<BatchJob[]>("/api/v1/batch/jobs");
export const getBatchJob = (id: string) => request<BatchJob>(`/api/v1/batch/jobs/${id}`);
export const getBatchRuns = () => request<BatchRun[]>("/api/v1/batch/runs");
export const getBatchRun = (id: string) => request<BatchRun>(`/api/v1/batch/runs/${id}`);
export const createBatchException = (id: string) => request<Record<string, unknown>>(`/api/v1/batch/runs/${id}/create-exception`, { method: "POST" });
export const createBatchTicket = (id: string) => request<{ id: string; ticket_number: string }>(`/api/v1/batch/runs/${id}/create-ticket`, { method: "POST" });
export const createBatchDiagnostic = (id: string) => request<{ id: string; diagnostic_number: string }>(`/api/v1/batch/runs/${id}/create-diagnostic`, { method: "POST" });
export function runBatchSimulation(code: string, payload: { create_exception: boolean; create_ticket: boolean; create_observability: boolean }) { return request<BatchSimulationResult>(`/api/v1/batch/simulations/${code}`, { method: "POST", body: JSON.stringify(payload) }); }
export function runBatchSuite(payload: { create_exception: boolean; create_ticket: boolean; create_observability: boolean }) { return request<BatchSuiteResult>("/api/v1/batch/simulations/batch-failure-suite", { method: "POST", body: JSON.stringify(payload) }); }
