const apiBaseUrl = (import.meta.env.VITE_API_BASE_URL || "http://localhost:8050").replace(/\/$/, "");

export interface SafeAction { id: string; action_code: string; name: string; description: string; target_module: string; action_type: string; risk_level: string; requires_human_approval: boolean; enabled: boolean; created_at: string; updated_at: string; }
export interface ContextSnapshot { id: string; session_id: string; snapshot_number: string; source_entity_type: string; source_entity_id: string | null; summary: string; impact_summary: string; technical_summary: string; business_summary: string; timeline_summary: string; evidence_summary: string; related_entities: Record<string, unknown> | null; raw_context: Record<string, unknown> | null; created_by: string; created_at: string; }
export interface Recommendation { id: string; session_id: string; snapshot_id: string | null; recommendation_type: string; title: string; details: string; priority: string; confidence_level: string; rationale: string; source_evidence: Record<string, unknown> | null; status: string; created_at: string; updated_at: string; accepted_at: string | null; dismissed_at: string | null; }
export interface ActionPlan { id: string; session_id: string; snapshot_id: string | null; plan_number: string; title: string; summary: string; status: string; steps: Array<Record<string, unknown>>; risk_level: string; requires_human_approval: boolean; created_at: string; updated_at: string; approved_at: string | null; completed_at: string | null; }
export interface CopilotMessage { id: string; session_id: string; message_type: string; title: string; content: string; status: string; target_entity_type: string | null; target_entity_id: string | null; ai_invocation_id: string | null; generation_mode: string | null; created_by: string; created_at: string; updated_at: string; }
export interface CopilotInvocation { id: string; invocation_number: string; provider_code: string | null; model_code: string | null; request_source: string; request_source_id: string | null; task_type: string; status: string; response_text: string | null; safety_status: string; blocked_reason: string | null; total_tokens_estimated: number; cost_estimated: number; created_at: string; }
export interface GovernedDraftResponse { message: CopilotMessage; invocation: CopilotInvocation; }
export interface CopilotActionEvent { id: string; session_id: string; action_code: string; event_type: string; target_entity_type: string | null; target_entity_id: string | null; from_status: string | null; to_status: string | null; message: string; event_payload: Record<string, unknown> | null; created_by: string; created_at: string; }
export interface CopilotSession { id: string; session_number: string; title: string; description: string; status: string; primary_entity_type: string; primary_entity_id: string | null; primary_ticket_id: string | null; severity: string; confidence_level: string; created_by: string; created_at: string; updated_at: string; closed_at: string | null; latest_context_snapshot: ContextSnapshot | null; recommendations: Recommendation[]; latest_action_plan: ActionPlan | null; messages: CopilotMessage[]; action_events: CopilotActionEvent[]; primary_entity_summary: string | null; }
export interface CopilotSummary { open_sessions: number; recommendations_proposed: number; recommendations_accepted: number; action_plans_ready: number; draft_messages: number; safe_actions_enabled: number; }

async function request<T>(path: string, options: RequestInit = {}): Promise<T> { const response = await fetch(apiBaseUrl + path, { ...options, headers: { "Content-Type": "application/json", ...(options.headers || {}) } }); const body = await response.json().catch(() => ({})); if (!response.ok) throw new Error(`Copilot API returned ${response.status}: ${typeof body === "object" && body?.detail ? body.detail : "request failed"}`); return body as T; }
export const getCopilotSummary = () => request<CopilotSummary>("/api/v1/copilot/summary");
export const getSafeActions = () => request<SafeAction[]>("/api/v1/copilot/safe-actions");
export const getCopilotSessions = () => request<CopilotSession[]>("/api/v1/copilot/sessions");
export const getCopilotSession = (id: string) => request<CopilotSession>(`/api/v1/copilot/sessions/${id}`);
export function createCopilotSession(payload: { title: string; description: string; primary_entity_type: string; primary_entity_id?: string | null; severity: string; build_context: boolean; generate_recommendations: boolean }) { return request<CopilotSession>("/api/v1/copilot/sessions", { method: "POST", body: JSON.stringify(payload) }); }
export const buildCopilotContext = (id: string) => request<ContextSnapshot>(`/api/v1/copilot/sessions/${id}/build-context`, { method: "POST" });
export const generateCopilotRecommendations = (id: string) => request<Recommendation[]>(`/api/v1/copilot/sessions/${id}/generate-recommendations`, { method: "POST" });
export const generateCopilotActionPlan = (id: string) => request<ActionPlan>(`/api/v1/copilot/sessions/${id}/generate-action-plan`, { method: "POST" });
export const generateCopilotMessage = (id: string, kind: "work-note" | "customer-update" | "investigation-checklist") => request<CopilotMessage>(`/api/v1/copilot/sessions/${id}/generate-${kind}`, { method: "POST" });
export const generateGovernedContextSummary = (id: string) => request<GovernedDraftResponse>(`/api/v1/copilot/sessions/${id}/generate-governed-context-summary`, { method: "POST" });
export const generateGovernedWorkNote = (id: string) => request<GovernedDraftResponse>(`/api/v1/copilot/sessions/${id}/generate-governed-work-note`, { method: "POST" });
export const generateGovernedCustomerUpdate = (id: string) => request<GovernedDraftResponse>(`/api/v1/copilot/sessions/${id}/generate-governed-customer-update`, { method: "POST" });
export const generateGovernedInvestigationChecklist = (id: string) => request<GovernedDraftResponse>(`/api/v1/copilot/sessions/${id}/generate-governed-investigation-checklist`, { method: "POST" });
export const getSessionAiInvocations = (id: string) => request<CopilotInvocation[]>(`/api/v1/copilot/sessions/${id}/ai-invocations`);
export const acceptCopilotRecommendation = (id: string) => request<Recommendation>(`/api/v1/copilot/recommendations/${id}/accept`, { method: "POST" });
export const dismissCopilotRecommendation = (id: string) => request<Recommendation>(`/api/v1/copilot/recommendations/${id}/dismiss`, { method: "POST" });
export const closeCopilotSession = (id: string) => request<CopilotSession>(`/api/v1/copilot/sessions/${id}/close`, { method: "POST" });
export const analyzeCopilot = (payload: { entity_type: string; entity_id?: string | null; title: string }) => request<CopilotSession>("/api/v1/copilot/analyze", { method: "POST", body: JSON.stringify(payload) });
