const apiBaseUrl = (import.meta.env.VITE_API_BASE_URL || "http://localhost:8050").replace(/\/$/, "");

export interface ObsSpan { id: string; span_id: string; parent_span_id: string | null; span_name: string; service_name: string; component_code: string | null; operation_type: string; status: string; started_at: string; ended_at: string | null; duration_ms: number | null; error_type: string | null; error_message: string | null; attributes: Record<string, unknown> | null; }
export interface ObsLog { id: string; log_number: string; trace_id: string | null; span_id: string | null; level: string; logger_name: string; message: string; event_type: string; source_module: string; component_code: string | null; entity_type: string | null; entity_id: string | null; linked_alert_id: string | null; linked_ticket_id: string | null; context: Record<string, unknown> | null; logged_at: string; created_at: string; }
export interface ObsMetric { id: string; sample_number: string; metric_name: string; metric_value: number; metric_unit: string; component_code: string | null; severity: string | null; trace_id: string | null; linked_alert_id: string | null; recorded_at: string; attributes: Record<string, unknown> | null; created_at: string; }
export interface ObsTrace { id: string; trace_id: string; trace_name: string; trace_type: string; status: string; source_module: string; root_entity_type: string | null; root_entity_id: string | null; root_reference: string | null; linked_alert_id: string | null; linked_triage_case_id: string | null; linked_ticket_id: string | null; started_at: string; ended_at: string | null; duration_ms: number | null; summary: string; spans: ObsSpan[]; logs: ObsLog[]; metrics: ObsMetric[]; }
export interface Evidence { id: string; evidence_type: string; source_table: string; source_id: string; title: string; details: string; weight: number; created_at: string; }
export interface DiagnosticCase { id: string; diagnostic_number: string; title: string; description: string; status: string; severity: string; source_type: string; source_id: string | null; linked_alert_id: string | null; linked_triage_case_id: string | null; linked_ticket_id: string | null; primary_trace_id: string | null; primary_trace_identifier: string | null; probable_cause: string; confidence_level: string; recommended_next_steps: string; diagnosis_summary: string; created_by: string; created_at: string; updated_at: string; resolved_at: string | null; evidence: Evidence[]; }
export interface ObsSummary { traces: number; error_traces: number; slow_spans: number; error_logs: number; metric_samples: number; open_diagnostic_cases: number; high_confidence_diagnoses: number; linked_tickets: number; }
export interface SimulationResult { simulation_code: string; trace_id: string | null; trace_identifier: string | null; diagnostic_case_id: string | null; diagnostic_number: string | null; alert_ids: string[]; ticket_id: string | null; tickets_created_or_linked: number; summary: string; }
export interface SuiteResult { simulation_code: string; traces_created: number; diagnostic_cases_created: number; alerts_created_or_reused: number; tickets_created_or_linked: number; highest_severity: string | null; summary: string; results: SimulationResult[]; }

async function request<T>(path: string, options: RequestInit = {}): Promise<T> { const response = await fetch(apiBaseUrl + path, { ...options, headers: { "Content-Type": "application/json", ...(options.headers || {}) } }); const body = await response.json().catch(() => ({})); if (!response.ok) throw new Error(`Observability API returned ${response.status}: ${typeof body === "object" && body?.detail ? body.detail : "request failed"}`); return body as T; }
export const getObservabilitySummary = () => request<ObsSummary>("/api/v1/observability/summary");
export const getTraces = () => request<ObsTrace[]>("/api/v1/observability/traces");
export const getTrace = (id: string) => request<ObsTrace>(`/api/v1/observability/traces/${id}`);
export const getLogs = () => request<ObsLog[]>("/api/v1/observability/log-events");
export const getMetrics = () => request<ObsMetric[]>("/api/v1/observability/metric-samples");
export const getDiagnosticCases = () => request<DiagnosticCase[]>("/api/v1/observability/diagnostic-cases");
export const getDiagnosticCase = (id: string) => request<DiagnosticCase>(`/api/v1/observability/diagnostic-cases/${id}`);
export const linkDiagnosticTicket = (id: string) => request<DiagnosticCase>(`/api/v1/observability/diagnostic-cases/${id}/link-ticket`, { method: "POST", body: "{}" });
export const resolveDiagnosticCase = (id: string, resolution_notes: string) => request<DiagnosticCase>(`/api/v1/observability/diagnostic-cases/${id}/resolve`, { method: "POST", body: JSON.stringify({ resolution_notes }) });
export const diagnosisFromAlert = (id: string) => request<DiagnosticCase>(`/api/v1/observability/diagnostics/from-alert/${id}`, { method: "POST" });
export const diagnosisFromTriageCase = (id: string) => request<DiagnosticCase>(`/api/v1/observability/diagnostics/from-triage-case/${id}`, { method: "POST" });
export const diagnosisFromTicket = (id: string) => request<DiagnosticCase>(`/api/v1/observability/diagnostics/from-ticket/${id}`, { method: "POST" });
export function runObservabilitySimulation(code: string, create_ticket = false) { return request<SimulationResult>(`/api/v1/observability/simulations/${code}`, { method: "POST", body: JSON.stringify({ create_ticket }) }); }
export const runObservabilitySuite = (create_ticket = false) => request<SuiteResult>("/api/v1/observability/simulations/observability-demo-suite", { method: "POST", body: JSON.stringify({ create_ticket }) });
