"""Add governed AI configuration, safety, invocation, and usage foundation."""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0010_governed_ai_config"
down_revision: Union[str, Sequence[str], None] = "0009_copilot_foundation"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

uuid_type = postgresql.UUID(as_uuid=True)
timestamp_type = sa.DateTime(timezone=True)
json_type = postgresql.JSONB


def upgrade() -> None:
    op.create_table("ai_providers", sa.Column("id", uuid_type, primary_key=True), sa.Column("provider_code", sa.String(100), nullable=False), sa.Column("name", sa.String(160), nullable=False), sa.Column("provider_type", sa.String(40), nullable=False), sa.Column("description", sa.String(1000), nullable=False), sa.Column("base_url", sa.String(500)), sa.Column("auth_type", sa.String(40), nullable=False, server_default="NONE"), sa.Column("enabled", sa.Boolean, nullable=False, server_default=sa.false()), sa.Column("is_mock", sa.Boolean, nullable=False, server_default=sa.false()), sa.Column("default_timeout_seconds", sa.Integer, nullable=False, server_default="30"), sa.Column("created_at", timestamp_type, nullable=False, server_default=sa.text("now()")), sa.Column("updated_at", timestamp_type, nullable=False, server_default=sa.text("now()")), sa.UniqueConstraint("provider_code", name="uq_ai_providers_code"))
    op.create_table("ai_model_configs", sa.Column("id", uuid_type, primary_key=True), sa.Column("model_code", sa.String(120), nullable=False), sa.Column("provider_id", uuid_type, sa.ForeignKey("ai_providers.id"), nullable=False), sa.Column("display_name", sa.String(160), nullable=False), sa.Column("model_name", sa.String(160), nullable=False), sa.Column("model_family", sa.String(80), nullable=False), sa.Column("purpose", sa.String(60), nullable=False), sa.Column("enabled", sa.Boolean, nullable=False, server_default=sa.false()), sa.Column("is_default", sa.Boolean, nullable=False, server_default=sa.false()), sa.Column("temperature", sa.Float, nullable=False, server_default="0"), sa.Column("top_p", sa.Float, nullable=False, server_default="1"), sa.Column("max_output_tokens", sa.Integer, nullable=False, server_default="1000"), sa.Column("context_window_tokens", sa.Integer, nullable=False, server_default="8000"), sa.Column("cost_per_1k_input_tokens", sa.Float, nullable=False, server_default="0"), sa.Column("cost_per_1k_output_tokens", sa.Float, nullable=False, server_default="0"), sa.Column("created_at", timestamp_type, nullable=False, server_default=sa.text("now()")), sa.Column("updated_at", timestamp_type, nullable=False, server_default=sa.text("now()")), sa.UniqueConstraint("model_code", name="uq_ai_model_configs_code"))
    op.create_table("ai_prompt_templates", sa.Column("id", uuid_type, primary_key=True), sa.Column("template_code", sa.String(120), nullable=False), sa.Column("name", sa.String(160), nullable=False), sa.Column("description", sa.String(1000), nullable=False), sa.Column("task_type", sa.String(60), nullable=False), sa.Column("template_version", sa.Integer, nullable=False, server_default="1"), sa.Column("system_template", sa.String(3000), nullable=False), sa.Column("user_template", sa.String(5000), nullable=False), sa.Column("input_schema", json_type), sa.Column("output_schema", json_type), sa.Column("enabled", sa.Boolean, nullable=False, server_default=sa.true()), sa.Column("is_default", sa.Boolean, nullable=False, server_default=sa.false()), sa.Column("created_at", timestamp_type, nullable=False, server_default=sa.text("now()")), sa.Column("updated_at", timestamp_type, nullable=False, server_default=sa.text("now()")), sa.UniqueConstraint("template_code", "template_version", name="uq_ai_prompt_templates_version"))
    op.create_table("ai_safety_policies", sa.Column("id", uuid_type, primary_key=True), sa.Column("policy_code", sa.String(100), nullable=False), sa.Column("name", sa.String(160), nullable=False), sa.Column("description", sa.String(1000), nullable=False), sa.Column("policy_scope", sa.String(60), nullable=False), sa.Column("enabled", sa.Boolean, nullable=False, server_default=sa.true()), sa.Column("blocking_mode", sa.String(20), nullable=False, server_default="BLOCK"), sa.Column("created_at", timestamp_type, nullable=False, server_default=sa.text("now()")), sa.Column("updated_at", timestamp_type, nullable=False, server_default=sa.text("now()")), sa.UniqueConstraint("policy_code", name="uq_ai_safety_policies_code"))
    op.create_table("ai_safety_policy_rules", sa.Column("id", uuid_type, primary_key=True), sa.Column("policy_id", uuid_type, sa.ForeignKey("ai_safety_policies.id"), nullable=False), sa.Column("rule_code", sa.String(100), nullable=False), sa.Column("name", sa.String(160), nullable=False), sa.Column("description", sa.String(1000), nullable=False), sa.Column("rule_type", sa.String(50), nullable=False), sa.Column("severity", sa.String(20), nullable=False, server_default="HIGH"), sa.Column("enabled", sa.Boolean, nullable=False, server_default=sa.true()), sa.Column("match_pattern", sa.String(200), nullable=False), sa.Column("action", sa.String(20), nullable=False, server_default="BLOCK"), sa.Column("created_at", timestamp_type, nullable=False, server_default=sa.text("now()")), sa.Column("updated_at", timestamp_type, nullable=False, server_default=sa.text("now()")), sa.UniqueConstraint("policy_id", "rule_code", name="uq_ai_safety_rules_policy_code"))
    op.create_table("ai_invocation_logs", sa.Column("id", uuid_type, primary_key=True), sa.Column("invocation_number", sa.String(100), nullable=False), sa.Column("provider_id", uuid_type, sa.ForeignKey("ai_providers.id")), sa.Column("model_config_id", uuid_type, sa.ForeignKey("ai_model_configs.id")), sa.Column("template_id", uuid_type, sa.ForeignKey("ai_prompt_templates.id")), sa.Column("policy_id", uuid_type, sa.ForeignKey("ai_safety_policies.id")), sa.Column("request_source", sa.String(80), nullable=False), sa.Column("request_source_id", uuid_type), sa.Column("task_type", sa.String(60), nullable=False), sa.Column("status", sa.String(20), nullable=False), sa.Column("input_summary", sa.String(2000), nullable=False), sa.Column("prompt_rendered", sa.String(10000), nullable=False), sa.Column("response_text", sa.String(10000)), sa.Column("response_json", json_type), sa.Column("safety_status", sa.String(20), nullable=False), sa.Column("blocked_reason", sa.String(1500)), sa.Column("latency_ms", sa.Integer, nullable=False, server_default="0"), sa.Column("input_tokens_estimated", sa.Integer, nullable=False, server_default="0"), sa.Column("output_tokens_estimated", sa.Integer, nullable=False, server_default="0"), sa.Column("total_tokens_estimated", sa.Integer, nullable=False, server_default="0"), sa.Column("cost_estimated", sa.Float, nullable=False, server_default="0"), sa.Column("created_by", sa.String(120), nullable=False, server_default="system"), sa.Column("created_at", timestamp_type, nullable=False, server_default=sa.text("now()")), sa.Column("updated_at", timestamp_type, nullable=False, server_default=sa.text("now()")), sa.UniqueConstraint("invocation_number", name="uq_ai_invocation_logs_number"))
    op.create_table("ai_usage_daily", sa.Column("id", uuid_type, primary_key=True), sa.Column("usage_date", sa.Date, nullable=False), sa.Column("provider_code", sa.String(100), nullable=False), sa.Column("model_code", sa.String(120), nullable=False), sa.Column("task_type", sa.String(60), nullable=False), sa.Column("invocation_count", sa.Integer, nullable=False, server_default="0"), sa.Column("blocked_count", sa.Integer, nullable=False, server_default="0"), sa.Column("input_tokens_estimated", sa.Integer, nullable=False, server_default="0"), sa.Column("output_tokens_estimated", sa.Integer, nullable=False, server_default="0"), sa.Column("total_tokens_estimated", sa.Integer, nullable=False, server_default="0"), sa.Column("cost_estimated", sa.Float, nullable=False, server_default="0"), sa.Column("created_at", timestamp_type, nullable=False, server_default=sa.text("now()")), sa.Column("updated_at", timestamp_type, nullable=False, server_default=sa.text("now()")), sa.UniqueConstraint("usage_date", "provider_code", "model_code", "task_type", name="uq_ai_usage_daily_key"))
    op.create_table("ai_guardrail_events", sa.Column("id", uuid_type, primary_key=True), sa.Column("invocation_id", uuid_type, sa.ForeignKey("ai_invocation_logs.id"), nullable=False), sa.Column("policy_id", uuid_type, sa.ForeignKey("ai_safety_policies.id")), sa.Column("rule_id", uuid_type, sa.ForeignKey("ai_safety_policy_rules.id")), sa.Column("event_type", sa.String(30), nullable=False), sa.Column("severity", sa.String(20), nullable=False), sa.Column("message", sa.String(1000), nullable=False), sa.Column("matched_text_summary", sa.String(300)), sa.Column("created_at", timestamp_type, nullable=False, server_default=sa.text("now()")))
    op.create_index("ix_ai_invocation_created", "ai_invocation_logs", ["created_at"])
    op.create_index("ix_ai_usage_date", "ai_usage_daily", ["usage_date"])
    op.create_index("ix_ai_guardrail_invocation", "ai_guardrail_events", ["invocation_id", "created_at"])


def downgrade() -> None:
    op.drop_index("ix_ai_guardrail_invocation", table_name="ai_guardrail_events")
    op.drop_index("ix_ai_usage_date", table_name="ai_usage_daily")
    op.drop_index("ix_ai_invocation_created", table_name="ai_invocation_logs")
    op.drop_table("ai_guardrail_events")
    op.drop_table("ai_usage_daily")
    op.drop_table("ai_invocation_logs")
    op.drop_table("ai_safety_policy_rules")
    op.drop_table("ai_safety_policies")
    op.drop_table("ai_prompt_templates")
    op.drop_table("ai_model_configs")
    op.drop_table("ai_providers")
