"""Add deterministic agent chat and case intake foundation."""

from alembic import op
import sqlalchemy as sa

revision = "0013_agent_chat_case_intake"
down_revision = "0012_observability_alerting"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.create_table("agent_cases", sa.Column("id", sa.Uuid(), primary_key=True), sa.Column("case_id", sa.String(100), unique=True, nullable=False), sa.Column("case_type", sa.String(50), nullable=False), sa.Column("title", sa.String(200), nullable=False), sa.Column("description", sa.String(2000), nullable=False), sa.Column("status", sa.String(30), nullable=False), sa.Column("priority", sa.String(10), nullable=False), sa.Column("source", sa.String(40), nullable=False), sa.Column("stage_mode", sa.String(40), nullable=False), sa.Column("created_by_role", sa.String(50), nullable=False), sa.Column("linked_ams_ticket_id", sa.Uuid(), sa.ForeignKey("ams_tickets.id")), sa.Column("linked_user_report_id", sa.Uuid(), sa.ForeignKey("ams_user_reports.id")), sa.Column("linked_alert_event_id", sa.Uuid(), sa.ForeignKey("obs_alert_events.id")), sa.Column("linked_batch_run_id", sa.Uuid(), sa.ForeignKey("batch_runs.id")), sa.Column("linked_diagnostic_case_id", sa.Uuid(), sa.ForeignKey("obs_diagnostic_cases.id")), sa.Column("linked_order_id", sa.Uuid(), sa.ForeignKey("wf_orders.id")), sa.Column("linked_shipment_id", sa.Uuid(), sa.ForeignKey("wf_shipments.id")), sa.Column("linked_inventory_item_id", sa.Uuid(), sa.ForeignKey("wf_items.id")), sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False), sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False), sa.Column("closed_at", sa.DateTime(timezone=True)))
    op.create_table("agent_chat_sessions", sa.Column("id", sa.Uuid(), primary_key=True), sa.Column("session_id", sa.String(100), unique=True, nullable=False), sa.Column("case_id", sa.Uuid(), sa.ForeignKey("agent_cases.id"), nullable=False), sa.Column("audience", sa.String(30), nullable=False), sa.Column("title", sa.String(200), nullable=False), sa.Column("status", sa.String(20), nullable=False), sa.Column("started_by_role", sa.String(50), nullable=False), sa.Column("experience", sa.String(30), nullable=False), sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False), sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False), sa.Column("closed_at", sa.DateTime(timezone=True)))
    op.create_table("agent_chat_messages", sa.Column("id", sa.Uuid(), primary_key=True), sa.Column("message_id", sa.String(100), unique=True, nullable=False), sa.Column("session_id", sa.Uuid(), sa.ForeignKey("agent_chat_sessions.id"), nullable=False), sa.Column("sender_type", sa.String(30), nullable=False), sa.Column("sender_role", sa.String(50), nullable=False), sa.Column("message_text", sa.String(6000), nullable=False), sa.Column("message_format", sa.String(30), nullable=False), sa.Column("generation_mode", sa.String(40), nullable=False), sa.Column("safety_status", sa.String(30), nullable=False), sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False), sa.Column("metadata_json", sa.JSON()))
    op.create_table("agent_orchestration_runs", sa.Column("id", sa.Uuid(), primary_key=True), sa.Column("run_id", sa.String(100), unique=True, nullable=False), sa.Column("case_id", sa.Uuid(), sa.ForeignKey("agent_cases.id"), nullable=False), sa.Column("session_id", sa.Uuid(), sa.ForeignKey("agent_chat_sessions.id"), nullable=False), sa.Column("trigger_message_id", sa.Uuid(), sa.ForeignKey("agent_chat_messages.id"), nullable=False), sa.Column("status", sa.String(30), nullable=False), sa.Column("stage_mode", sa.String(40), nullable=False), sa.Column("orchestrator_mode", sa.String(50), nullable=False), sa.Column("started_at", sa.DateTime(timezone=True), nullable=False), sa.Column("completed_at", sa.DateTime(timezone=True)), sa.Column("summary", sa.String(3000), nullable=False), sa.Column("error_message", sa.String(1000)), sa.Column("tools_planned", sa.JSON()), sa.Column("tools_used", sa.JSON()), sa.Column("actions_proposed", sa.Integer(), nullable=False), sa.Column("actions_executed", sa.Integer(), nullable=False))
    op.create_table("agent_evidence_items", sa.Column("id", sa.Uuid(), primary_key=True), sa.Column("evidence_id", sa.String(100), unique=True, nullable=False), sa.Column("case_id", sa.Uuid(), sa.ForeignKey("agent_cases.id"), nullable=False), sa.Column("run_id", sa.Uuid(), sa.ForeignKey("agent_orchestration_runs.id"), nullable=False), sa.Column("evidence_type", sa.String(50), nullable=False), sa.Column("source_type", sa.String(50), nullable=False), sa.Column("source_id", sa.Uuid()), sa.Column("title", sa.String(200), nullable=False), sa.Column("summary", sa.String(1500), nullable=False), sa.Column("payload_json", sa.JSON()), sa.Column("source_url", sa.String(500)), sa.Column("relevance_score", sa.Float(), nullable=False), sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False))
    op.create_table("agent_action_proposals", sa.Column("id", sa.Uuid(), primary_key=True), sa.Column("proposal_id", sa.String(100), unique=True, nullable=False), sa.Column("case_id", sa.Uuid(), sa.ForeignKey("agent_cases.id"), nullable=False), sa.Column("run_id", sa.Uuid(), sa.ForeignKey("agent_orchestration_runs.id"), nullable=False), sa.Column("title", sa.String(200), nullable=False), sa.Column("description", sa.String(1000), nullable=False), sa.Column("action_type", sa.String(60), nullable=False), sa.Column("risk_level", sa.String(20), nullable=False), sa.Column("status", sa.String(30), nullable=False), sa.Column("requires_approval", sa.Boolean(), nullable=False), sa.Column("approval_status", sa.String(30), nullable=False), sa.Column("execution_status", sa.String(40), nullable=False), sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False), sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False))


def downgrade() -> None:
    op.drop_table("agent_action_proposals")
    op.drop_table("agent_evidence_items")
    op.drop_table("agent_orchestration_runs")
    op.drop_table("agent_chat_messages")
    op.drop_table("agent_chat_sessions")
    op.drop_table("agent_cases")
