"""Add deterministic agent knowledge and retrieval audit foundation."""

from alembic import op
import sqlalchemy as sa

revision = "0014_agent_knowledge_rag"
down_revision = "0013_agent_chat_case_intake"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.create_table("agent_knowledge_sources", sa.Column("id", sa.Uuid(), primary_key=True), sa.Column("source_id", sa.String(100), unique=True, nullable=False), sa.Column("source_code", sa.String(100), unique=True, nullable=False), sa.Column("name", sa.String(200), nullable=False), sa.Column("description", sa.String(1000), nullable=False), sa.Column("source_type", sa.String(60), nullable=False), sa.Column("owner", sa.String(120), nullable=False), sa.Column("status", sa.String(20), nullable=False), sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False), sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False))
    op.create_table("agent_knowledge_articles", sa.Column("id", sa.Uuid(), primary_key=True), sa.Column("article_id", sa.String(100), unique=True, nullable=False), sa.Column("source_id", sa.Uuid(), sa.ForeignKey("agent_knowledge_sources.id"), nullable=False), sa.Column("article_code", sa.String(100), unique=True, nullable=False), sa.Column("title", sa.String(250), nullable=False), sa.Column("summary", sa.String(1000), nullable=False), sa.Column("body", sa.String(12000), nullable=False), sa.Column("article_type", sa.String(50), nullable=False), sa.Column("domain", sa.String(50), nullable=False), sa.Column("application_area", sa.String(100), nullable=False), sa.Column("severity_applicability", sa.String(200)), sa.Column("status", sa.String(20), nullable=False), sa.Column("version", sa.Integer(), nullable=False), sa.Column("tags", sa.JSON()), sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False), sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False))
    op.create_table("agent_knowledge_chunks", sa.Column("id", sa.Uuid(), primary_key=True), sa.Column("chunk_id", sa.String(120), unique=True, nullable=False), sa.Column("article_id", sa.Uuid(), sa.ForeignKey("agent_knowledge_articles.id"), nullable=False), sa.Column("chunk_index", sa.Integer(), nullable=False), sa.Column("heading", sa.String(200), nullable=False), sa.Column("chunk_text", sa.String(4000), nullable=False), sa.Column("normalized_text", sa.String(4000), nullable=False), sa.Column("token_count_estimate", sa.Integer(), nullable=False), sa.Column("keywords", sa.JSON()), sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False), sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False), sa.UniqueConstraint("article_id", "chunk_index", name="uq_agent_knowledge_chunk_index"))
    op.create_table("agent_known_errors", sa.Column("id", sa.Uuid(), primary_key=True), sa.Column("known_error_id", sa.String(100), unique=True, nullable=False), sa.Column("error_code", sa.String(100), unique=True, nullable=False), sa.Column("title", sa.String(250), nullable=False), sa.Column("symptoms", sa.String(1500), nullable=False), sa.Column("likely_cause", sa.String(1500), nullable=False), sa.Column("workaround", sa.String(1500), nullable=False), sa.Column("permanent_fix", sa.String(1500)), sa.Column("affected_area", sa.String(100), nullable=False), sa.Column("severity", sa.String(20), nullable=False), sa.Column("status", sa.String(20), nullable=False), sa.Column("related_article_id", sa.Uuid(), sa.ForeignKey("agent_knowledge_articles.id")), sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False), sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False))
    op.create_table("agent_retrieval_queries", sa.Column("id", sa.Uuid(), primary_key=True), sa.Column("query_id", sa.String(100), unique=True, nullable=False), sa.Column("case_id", sa.Uuid(), sa.ForeignKey("agent_cases.id")), sa.Column("session_id", sa.Uuid(), sa.ForeignKey("agent_chat_sessions.id")), sa.Column("message_id", sa.Uuid(), sa.ForeignKey("agent_chat_messages.id")), sa.Column("query_text", sa.String(3000), nullable=False), sa.Column("normalized_query", sa.String(3000), nullable=False), sa.Column("retrieval_mode", sa.String(50), nullable=False), sa.Column("top_k", sa.Integer(), nullable=False), sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False))
    op.create_table("agent_retrieval_results", sa.Column("id", sa.Uuid(), primary_key=True), sa.Column("result_id", sa.String(100), unique=True, nullable=False), sa.Column("query_id", sa.Uuid(), sa.ForeignKey("agent_retrieval_queries.id"), nullable=False), sa.Column("article_id", sa.Uuid(), sa.ForeignKey("agent_knowledge_articles.id")), sa.Column("chunk_id", sa.Uuid(), sa.ForeignKey("agent_knowledge_chunks.id")), sa.Column("known_error_id", sa.Uuid(), sa.ForeignKey("agent_known_errors.id")), sa.Column("rank", sa.Integer(), nullable=False), sa.Column("score", sa.Float(), nullable=False), sa.Column("match_reason", sa.String(1000), nullable=False), sa.Column("snippet", sa.String(1200), nullable=False), sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False))


def downgrade() -> None:
    op.drop_table("agent_retrieval_results")
    op.drop_table("agent_retrieval_queries")
    op.drop_table("agent_known_errors")
    op.drop_table("agent_knowledge_chunks")
    op.drop_table("agent_knowledge_articles")
    op.drop_table("agent_knowledge_sources")
