import { useState } from "react";
import { useMutation, useQuery } from "@tanstack/react-query";
import { Alert, Box, Button, Card, CardContent, Chip, CircularProgress, Grid, Paper, Table, TableBody, TableCell, TableContainer, TableHead, TableRow, TextField, Typography } from "@mui/material";
import { Link, useParams } from "react-router-dom";
import { getKnowledgeArticle, getKnowledgeArticles, getKnowledgeSources, getKnowledgeSummary, getKnownError, getKnownErrors, getRetrievalQueries, getRetrievalQuery, searchKnowledge, type KnowledgeArticle, type RetrievalResult } from "../services/agentKnowledgeApi";

function Header({ title }: { title: string }) { return <><Typography variant="overline" color="primary">Agent Knowledge and RAG Foundation</Typography><Typography variant="h3" sx={{ fontWeight: 700, mb: 1 }}>{title}</Typography><Alert severity="info" sx={{ mb: 3 }}>Deterministic keyword retrieval only. No external LLM call, embedding model, or vector database is used.</Alert></>; }
function State({ loading, error }: { loading: boolean; error: Error | null }) { if (loading) return <Box sx={{ display: "flex", gap: 1, alignItems: "center", mb: 2 }}><CircularProgress size={20} />Loading knowledge…</Box>; if (error) return <Alert severity="error" sx={{ mb: 2 }}>{error.message}</Alert>; return null; }
function Result({ result }: { result: RetrievalResult }) { return <Paper sx={{ p: 2, mb: 1 }}><Typography fontWeight={700}>{result.article_title || result.known_error_code} {result.heading ? `· ${result.heading}` : ""}</Typography><Typography variant="body2" color="text.secondary">Rank {result.rank} · score {result.score} · {result.match_reason}</Typography><Typography sx={{ mt: 1 }}>{result.snippet}</Typography></Paper>; }

export function AgentKnowledgeHomePage() { const summary = useQuery({ queryKey: ["agent-knowledge", "summary"], queryFn: getKnowledgeSummary }); return <Box><Header title="Agent Knowledge" /><Typography color="text.secondary" sx={{ mb: 3 }}>Curated runbooks, SOPs, known errors, and retrieval audit provide the deterministic context layer for future RAG.</Typography><State loading={summary.isLoading} error={summary.error as Error | null} />{summary.data && <Grid container spacing={2}>{[["Sources", summary.data.sources], ["Active articles", summary.data.active_articles], ["Searchable chunks", summary.data.chunks], ["Known errors", summary.data.known_errors], ["Retrieval queries", summary.data.retrieval_queries], ["Retrieval results", summary.data.retrieval_results]].map(([label, value]) => <Grid size={{ xs: 6, md: 2 }} key={String(label)}><Card><CardContent><Typography color="text.secondary">{label}</Typography><Typography variant="h4">{value}</Typography></CardContent></Card></Grid>)}</Grid>}<Box sx={{ mt: 4, display: "flex", gap: 2, flexWrap: "wrap" }}><Button component={Link} variant="contained" to="/agent-knowledge/search">Search Knowledge</Button><Button component={Link} variant="outlined" to="/agent-knowledge/articles">Browse Articles</Button><Button component={Link} variant="outlined" to="/agent-knowledge/known-errors">Known Errors</Button></Box></Box>; }

export function AgentKnowledgeSearchPage() { const [text, setText] = useState(""); const search = useMutation({ mutationFn: () => searchKnowledge(text) }); return <Box><Header title="Search Knowledge" /><TextField fullWidth multiline minRows={2} label="Issue or support question" value={text} onChange={(event) => setText(event.target.value)} placeholder="order is stuck during fulfillment and inventory allocation failed" /><Button sx={{ mt: 2, mb: 3 }} variant="contained" disabled={search.isPending || !text.trim()} onClick={() => search.mutate()}>Search</Button>{search.error && <Alert severity="error">{(search.error as Error).message}</Alert>}{search.data && <><Typography color="text.secondary" sx={{ mb: 2 }}>{search.data.retrieval_mode} · query {search.data.query_id}</Typography>{search.data.notes.map((note) => <Alert key={note} severity="info" sx={{ mb: 2 }}>{note}</Alert>)}{search.data.results.map((result) => <Result result={result} key={result.result_id} />)}</>}</Box>; }

export function AgentKnowledgeArticlesPage() { const articles = useQuery({ queryKey: ["agent-knowledge", "articles"], queryFn: getKnowledgeArticles }); return <Box><Header title="Knowledge Articles" /><State loading={articles.isLoading} error={articles.error as Error | null} /><TableContainer component={Paper}><Table><TableHead><TableRow>{["Article", "Type", "Domain", "Area", "Version"].map((item) => <TableCell key={item}>{item}</TableCell>)}</TableRow></TableHead><TableBody>{articles.data?.map((article) => <TableRow key={article.id}><TableCell><Link to={`/agent-knowledge/articles/${article.id}`}>{article.title}</Link><Typography variant="body2">{article.article_code}</Typography></TableCell><TableCell>{article.article_type}</TableCell><TableCell>{article.domain}</TableCell><TableCell>{article.application_area}</TableCell><TableCell>{article.version}</TableCell></TableRow>)}</TableBody></Table></TableContainer></Box>; }

export function AgentKnowledgeArticleDetailPage() { const { articleId = "" } = useParams(); const article = useQuery({ queryKey: ["agent-knowledge", "article", articleId], queryFn: () => getKnowledgeArticle(articleId), enabled: Boolean(articleId) }); return <Box><Header title="Knowledge Article" /><State loading={article.isLoading} error={article.error as Error | null} />{article.data && <ArticleDetail article={article.data} />}</Box>; }
function ArticleDetail({ article }: { article: KnowledgeArticle }) { return <><Card sx={{ mb: 3 }}><CardContent><Typography variant="h5">{article.title}</Typography><Typography color="text.secondary">{article.article_id} · {article.article_type} · {article.domain}</Typography><Typography sx={{ mt: 2 }}>{article.summary}</Typography><Chip sx={{ mt: 2 }} label={`v${article.version}`} /></CardContent></Card><Typography variant="h5" sx={{ mb: 2 }}>Chunks</Typography>{article.chunks.map((chunk) => <Paper key={chunk.id} sx={{ p: 2, mb: 1 }}><Typography fontWeight={700}>{chunk.heading}</Typography><Typography>{chunk.chunk_text}</Typography><Typography variant="caption" color="text.secondary">{chunk.chunk_id} · approximately {chunk.token_count_estimate} words</Typography></Paper>)}</>; }

export function AgentKnownErrorsPage() { const errors = useQuery({ queryKey: ["agent-knowledge", "known-errors"], queryFn: getKnownErrors }); return <Box><Header title="Known Errors" /><State loading={errors.isLoading} error={errors.error as Error | null} /><TableContainer component={Paper}><Table><TableHead><TableRow>{["Code", "Title", "Area", "Severity", "Symptoms", "Workaround"].map((item) => <TableCell key={item}>{item}</TableCell>)}</TableRow></TableHead><TableBody>{errors.data?.map((error) => <TableRow key={error.id}><TableCell><Link to={`/agent-knowledge/known-errors/${error.id}`}>{error.error_code}</Link></TableCell><TableCell>{error.title}</TableCell><TableCell>{error.affected_area}</TableCell><TableCell>{error.severity}</TableCell><TableCell>{error.symptoms}</TableCell><TableCell>{error.workaround}</TableCell></TableRow>)}</TableBody></Table></TableContainer></Box>; }
export function AgentKnownErrorDetailPage() { const { knownErrorId = "" } = useParams(); const item = useQuery({ queryKey: ["agent-knowledge", "known-error", knownErrorId], queryFn: () => getKnownError(knownErrorId), enabled: Boolean(knownErrorId) }); return <Box><Header title="Known Error Detail" /><State loading={item.isLoading} error={item.error as Error | null} />{item.data && <Card><CardContent><Typography variant="h5">{item.data.error_code}: {item.data.title}</Typography><Typography sx={{ mt: 2 }}><strong>Symptoms:</strong> {item.data.symptoms}</Typography><Typography sx={{ mt: 1 }}><strong>Likely cause:</strong> {item.data.likely_cause}</Typography><Typography sx={{ mt: 1 }}><strong>Workaround:</strong> {item.data.workaround}</Typography></CardContent></Card>}</Box>; }

export function AgentRetrievalQueriesPage() { const queries = useQuery({ queryKey: ["agent-knowledge", "retrieval-queries"], queryFn: getRetrievalQueries }); return <Box><Header title="Retrieval Audit" /><State loading={queries.isLoading} error={queries.error as Error | null} /><TableContainer component={Paper}><Table><TableHead><TableRow>{["Query", "Text", "Mode", "Top K", "Results", "Created"].map((item) => <TableCell key={item}>{item}</TableCell>)}</TableRow></TableHead><TableBody>{queries.data?.map((query) => <TableRow key={query.id}><TableCell><Link to={`/agent-knowledge/retrieval-queries/${query.query_id}`}>{query.query_id}</Link></TableCell><TableCell>{query.query_text}</TableCell><TableCell>{query.retrieval_mode}</TableCell><TableCell>{query.top_k}</TableCell><TableCell>{query.results.length}</TableCell><TableCell>{new Date(query.created_at).toLocaleString()}</TableCell></TableRow>)}</TableBody></Table></TableContainer></Box>; }
export function AgentRetrievalQueryDetailPage() { const { queryId = "" } = useParams(); const query = useQuery({ queryKey: ["agent-knowledge", "retrieval-query", queryId], queryFn: () => getRetrievalQuery(queryId), enabled: Boolean(queryId) }); return <Box><Header title="Retrieval Query Detail" /><State loading={query.isLoading} error={query.error as Error | null} />{query.data && <><Typography color="text.secondary" sx={{ mb: 2 }}>{query.data.query_id} · {query.data.query_text}</Typography>{query.data.results.map((result) => <Result result={result} key={result.result_id} />)}</>}</Box>; }

export function AgentKnowledgeSourcesPage() { const sources = useQuery({ queryKey: ["agent-knowledge", "sources"], queryFn: getKnowledgeSources }); return <Box><Header title="Knowledge Sources" /><State loading={sources.isLoading} error={sources.error as Error | null} /><TableContainer component={Paper}><Table><TableHead><TableRow>{["Name", "Code", "Type", "Owner", "Status"].map((item) => <TableCell key={item}>{item}</TableCell>)}</TableRow></TableHead><TableBody>{sources.data?.map((source) => <TableRow key={source.id}><TableCell>{source.name}</TableCell><TableCell>{source.source_code}</TableCell><TableCell>{source.source_type}</TableCell><TableCell>{source.owner}</TableCell><TableCell>{source.status}</TableCell></TableRow>)}</TableBody></Table></TableContainer></Box>; }
