import { useState } from "react";
import { useQuery } from "@tanstack/react-query";
import { Alert, Box, Button, Card, CardContent, Chip, CircularProgress, Grid, Paper, Stack, Table, TableBody, TableCell, TableContainer, TableHead, TableRow, TextField, Typography } from "@mui/material";
import { Link } from "react-router-dom";
import { getBaselineSummary, getHandoverMarkdown, getLimitations, getRequirements, getSignoff, getWalkthroughs, type Requirement, type Walkthrough } from "../services/baselineCompletionApi";

function State({ loading, error }: { loading: boolean; error: Error | null }) { if (loading) return <Box sx={{ display: "flex", gap: 1, alignItems: "center", mb: 2 }}><CircularProgress size={20} />Loading baseline completion pack…</Box>; if (error) return <Alert severity="error" sx={{ mb: 2 }}>{error.message}</Alert>; return null; }
function Safety() { return <Alert severity="info" sx={{ mb: 3 }}>Baseline 1.0 is a read-only handover layer. Real model calls and Stage 3 execution remain disabled by default; no ServiceNow, authentication, shell, SQL, or external execution is included.</Alert>; }
function NavLinks() { return <Stack direction="row" gap={1} flexWrap="wrap" sx={{ mb: 3 }}><Button component={Link} to="/baseline-completion/requirements">Requirements</Button><Button component={Link} to="/baseline-completion/walkthroughs">Walkthroughs</Button><Button component={Link} to="/baseline-completion/handover">Handover</Button><Button component={Link} to="/baseline-completion/limitations">Limitations</Button><Button component={Link} to="/baseline-completion/signoff">Sign-off</Button></Stack>; }

export function BaselineCompletionPage() { const query = useQuery({ queryKey: ["baseline-completion", "summary"], queryFn: getBaselineSummary }); return <Box><Typography variant="overline" color="primary">Final demo handover</Typography><Typography variant="h2" sx={{ fontWeight: 700, mb: 1 }}>{query.data?.baseline_name || "Baseline Completion"}</Typography><Typography color="text.secondary" sx={{ mb: 3 }}>A consolidated, presenter-friendly map of the EOS baseline demo.</Typography><Safety /><State loading={query.isLoading} error={query.error as Error | null} />{query.data && <><Stack direction="row" gap={1} flexWrap="wrap" sx={{ mb: 3 }}><Chip color="success" label={`${query.data.completion_status} · ${query.data.baseline_version}`} /><Chip color="success" variant="outlined" label="Real model default: Off" /><Chip color="success" variant="outlined" label="Stage 3 execution default: Off" /><Chip color="success" variant="outlined" label="ServiceNow: Absent" /><Chip color="success" variant="outlined" label="Authentication: Absent" /></Stack><Grid container spacing={2} sx={{ mb: 3 }}>{[["Completed range", query.data.completed_prompt_range], ["Capabilities", query.data.capability_count], ["Scenarios", query.data.scenario_count], ["Stage modes", query.data.stage_modes_supported.length]].map(([label, value]) => <Grid size={{ xs: 6, md: 3 }} key={String(label)}><Card><CardContent><Typography color="text.secondary">{label}</Typography><Typography variant="h5" sx={{ mt: 1 }}>{value}</Typography></CardContent></Card></Grid>)}</Grid><Card sx={{ mb: 3 }}><CardContent><Typography variant="h5">Recommended demo flow</Typography>{query.data.recommended_demo_flow.map((step, index) => <Typography key={step} sx={{ mt: 1 }}>{index + 1}. {step}</Typography>)}<Typography variant="body2" color="text.secondary" sx={{ mt: 2 }}>Start at {query.data.recommended_start_url}</Typography></CardContent></Card><NavLinks /></>}</Box>; }

export function BaselineRequirementsPage() { const query = useQuery({ queryKey: ["baseline-completion", "requirements"], queryFn: getRequirements }); const [filter, setFilter] = useState(""); const rows = (query.data?.requirements || []).filter((row: Requirement) => `${row.category} ${row.status} ${row.requirement}`.toLowerCase().includes(filter.toLowerCase())); return <Box><Typography variant="h3" sx={{ fontWeight: 700, mb: 1 }}>Requirements Traceability</Typography><Typography color="text.secondary" sx={{ mb: 3 }}>Prompt-level coverage with UI/API evidence and explicit out-of-scope boundaries.</Typography><Safety /><State loading={query.isLoading} error={query.error as Error | null} />{query.data && <><Stack direction={{ xs: "column", md: "row" }} gap={2} sx={{ mb: 2 }}><TextField label="Filter category, status, or requirement" value={filter} onChange={(event) => setFilter(event.target.value)} fullWidth /><Chip label={`${query.data.summary.covered} covered · ${query.data.summary.out_of_scope} out of scope`} /></Stack><TableContainer component={Paper}><Table size="small"><TableHead><TableRow>{["ID", "Category", "Requirement", "Status", "Prompts", "UI/API evidence", "Tests"].map((header) => <TableCell key={header}>{header}</TableCell>)}</TableRow></TableHead><TableBody>{rows.map((row) => <TableRow key={row.requirement_id}><TableCell>{row.requirement_id}</TableCell><TableCell>{row.category}</TableCell><TableCell>{row.requirement}<Typography variant="caption" display="block" color="text.secondary">{row.notes}</Typography></TableCell><TableCell><Chip size="small" color={row.status === "COVERED" ? "success" : "warning"} label={row.status} /></TableCell><TableCell>{row.implemented_by_prompts.join(", ")}</TableCell><TableCell>{row.primary_ui_routes.join(", ")}<br />{row.primary_api_routes.join(", ")}</TableCell><TableCell>{row.test_coverage}</TableCell></TableRow>)}</TableBody></Table></TableContainer></>}</Box>; }

export function BaselineWalkthroughsPage() { const query = useQuery({ queryKey: ["baseline-completion", "walkthroughs"], queryFn: getWalkthroughs }); return <Box><Typography variant="h3" sx={{ fontWeight: 700, mb: 1 }}>UI Walkthrough Pack</Typography><Typography color="text.secondary" sx={{ mb: 3 }}>Click-by-click, browser-first demo and handover paths.</Typography><Safety /><State loading={query.isLoading} error={query.error as Error | null} />{query.data?.walkthroughs.map((walkthrough: Walkthrough) => <Card sx={{ mb: 2 }} key={walkthrough.walkthrough_id}><CardContent><Stack direction={{ xs: "column", md: "row" }} justifyContent="space-between"><Typography variant="h5">{walkthrough.title}</Typography><Chip label={`${walkthrough.estimated_duration_minutes} min · ${walkthrough.start_experience}`} /></Stack><Typography color="text.secondary" sx={{ mt: 1 }}>{walkthrough.audience} · Start: {walkthrough.start_url}</Typography>{walkthrough.steps.map((step) => <Paper sx={{ p: 1.5, mt: 1 }} key={step.step_number}><Typography fontWeight={700}>Step {step.step_number}: {step.instruction}</Typography><Typography variant="body2"><strong>Click:</strong> {step.what_to_click} · <strong>Page:</strong> {step.page_url}</Typography><Typography variant="body2"><strong>Expected:</strong> {step.expected_result}</Typography><Typography variant="body2" color="text.secondary"><strong>Capture:</strong> {step.evidence_to_capture}</Typography></Paper>)}<Typography variant="body2" sx={{ mt: 1 }}><strong>Reset:</strong> {walkthrough.reset_instructions}</Typography></CardContent></Card>)}</Box>; }

export function BaselineHandoverPage() { const pack = useQuery({ queryKey: ["baseline-completion", "handover"], queryFn: getHandoverMarkdown }); const [copied, setCopied] = useState(false); const copy = async () => { if (pack.data) { await navigator.clipboard?.writeText(pack.data); setCopied(true); } }; return <Box><Typography variant="h3" sx={{ fontWeight: 700, mb: 1 }}>Handover Pack</Typography><Typography color="text.secondary" sx={{ mb: 3 }}>Generated from the same baseline service data as the JSON APIs.</Typography><Safety /><State loading={pack.isLoading} error={pack.error as Error | null} />{pack.data && <><Button variant="contained" onClick={() => void copy()}>Copy Markdown</Button>{copied && <Chip color="success" label="Copied" sx={{ ml: 1 }} />}<Paper component="pre" sx={{ p: 2, mt: 2, overflow: "auto", whiteSpace: "pre-wrap", maxHeight: "70vh" }}>{pack.data}</Paper></>}</Box>; }

export function BaselineLimitationsPage() { const query = useQuery({ queryKey: ["baseline-completion", "limitations"], queryFn: getLimitations }); return <Box><Typography variant="h3" sx={{ fontWeight: 700, mb: 1 }}>Known Limitations</Typography><Typography color="text.secondary" sx={{ mb: 3 }}>Boundaries to keep visible during customer and technical handover.</Typography><Safety /><State loading={query.isLoading} error={query.error as Error | null} />{query.data?.limitations.map((item) => <Card sx={{ mb: 2 }} key={item.limitation_id}><CardContent><Stack direction="row" justifyContent="space-between" gap={1}><Typography variant="h6">{item.description}</Typography><Chip color="warning" size="small" label={item.status} /></Stack><Typography sx={{ mt: 1 }}>{item.impact}</Typography><Typography variant="body2" color="text.secondary" sx={{ mt: 1 }}>Recommended: {item.future_phase_recommendation}</Typography></CardContent></Card>)}</Box>; }

export function BaselineSignoffPage() { const query = useQuery({ queryKey: ["baseline-completion", "signoff"], queryFn: getSignoff }); return <Box><Typography variant="h3" sx={{ fontWeight: 700, mb: 1 }}>Final Sign-off Checklist</Typography><Typography color="text.secondary" sx={{ mb: 3 }}>Read-only evidence routes for Baseline 1.0 handover.</Typography><Safety /><State loading={query.isLoading} error={query.error as Error | null} />{query.data?.sections.map((section) => <Card sx={{ mb: 2 }} key={section.area}><CardContent><Typography variant="h5">{section.area}</Typography>{section.items.map((item) => <Paper sx={{ p: 1.5, mt: 1 }} key={item.item}><Stack direction={{ xs: "column", md: "row" }} justifyContent="space-between"><Typography fontWeight={700}>{item.item}</Typography><Chip size="small" color={item.status === "READY" ? "success" : "warning"} label={item.status} /></Stack><Typography variant="body2">Evidence: {item.evidence_url_or_route}</Typography><Typography variant="body2" color="text.secondary">Validation: {item.validation_method}</Typography></Paper>)}</CardContent></Card>)}</Box>; }
