import { useState } from "react";
import { Link } from "react-router-dom";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Alert, Box, Button, Card, CardContent, Chip, CircularProgress, FormControl, Grid, InputLabel, MenuItem, Paper, Select, Stack, Table, TableBody, TableCell, TableContainer, TableHead, TableRow, Typography } from "@mui/material";
import { getExperienceCode } from "../config/experience";
import { getDemoReadinessChecks, getDemoReadinessGuide, getDemoReadinessShowcase, getDemoReadinessSummary, getDemoReadinessUrls, getDemoResetProfiles, getDemoSmokeReport, prepareDemoShowcase, resetDemoReadiness, type LauncherUrl, type ReadinessCheck } from "../services/demoReadinessApi";

function State({ loading, error }: { loading: boolean; error: Error | null }) { if (loading) return <Box sx={{ display: "flex", gap: 1, alignItems: "center", mb: 2 }}><CircularProgress size={20} />Checking local demo readiness…</Box>; if (error) return <Alert severity="error" sx={{ mb: 2 }}>{error.message}</Alert>; return null; }
function SafetyBanner() { return <Alert severity="warning" sx={{ mb: 3 }}>Local EOS demo data only. Real model calls are disabled by default, autonomous remediation is disabled, and reset never drops the database or deletes audit history.</Alert>; }
function StatusBadges({ summary }: { summary: Awaited<ReturnType<typeof getDemoReadinessSummary>> }) { return <Stack direction="row" gap={1} flexWrap="wrap" sx={{ mb: 3 }}><Chip color={summary.status === "READY" ? "success" : "warning"} label={`${summary.status} · ${summary.readiness_score}/100`} /><Chip color="success" variant="outlined" label={`Real model default: ${summary.real_model_default_enabled ? "On" : "Off"}`} /><Chip color="success" variant="outlined" label="Autonomous remediation: Disabled" /><Chip color="success" variant="outlined" label="ServiceNow: Not configured" /></Stack>; }
function UrlList({ urls }: { urls: LauncherUrl[] }) { return <Stack spacing={1}>{urls.sort((a, b) => a.recommended_order - b.recommended_order).map((item) => <Paper key={item.label} sx={{ p: 1.5 }}><Stack direction={{ xs: "column", md: "row" }} justifyContent="space-between" gap={1}><Box><Typography fontWeight={700}>{item.label}</Typography><Typography variant="body2" color="text.secondary">{item.description} · {item.experience}</Typography></Box><Button component="a" href={item.url} target="_blank" rel="noreferrer" size="small">Open</Button></Stack></Paper>)}</Stack>; }

export function DemoReadinessPage() {
  const summary = useQuery({ queryKey: ["demo-readiness", "summary"], queryFn: getDemoReadinessSummary });
  const checks = useQuery({ queryKey: ["demo-readiness", "checks"], queryFn: getDemoReadinessChecks });
  const error = (summary.error || checks.error) as Error | null;
  return <Box><Typography variant="overline" color="primary">Repeatable showcase operations</Typography><Typography variant="h3" sx={{ fontWeight: 700, mb: 1 }}>Demo Readiness</Typography><Typography color="text.secondary" sx={{ mb: 3 }}>One place to verify the local EOS environment before a customer walkthrough.</Typography><SafetyBanner /><State loading={summary.isLoading || checks.isLoading} error={error} />{summary.data && <><StatusBadges summary={summary.data} /><Grid container spacing={2} sx={{ mb: 3 }}>{[["Readiness score", `${summary.data.readiness_score}/100`], ["Critical checks passed", summary.data.critical_checks_passed], ["Critical checks failed", summary.data.critical_checks_failed], ["Demo mode", summary.data.demo_mode]].map(([label, value]) => <Grid size={{ xs: 6, md: 3 }} key={String(label)}><Card><CardContent><Typography color="text.secondary">{label}</Typography><Typography variant="h4" sx={{ mt: 1 }}>{value}</Typography></CardContent></Card></Grid>)}</Grid><Card sx={{ mb: 3 }}><CardContent><Typography variant="h5">Recommended next action</Typography><Typography sx={{ mt: 1 }}>{summary.data.recommended_next_action}</Typography>{summary.data.warnings.map((warning) => <Alert severity="info" sx={{ mt: 1 }} key={warning}>{warning}</Alert>)}</CardContent></Card></>}{checks.data && <Card><CardContent><Typography variant="h5" sx={{ mb: 1 }}>Readiness checks</Typography><TableContainer><Table size="small"><TableHead><TableRow>{["Check", "Critical", "Status", "Message"].map((header) => <TableCell key={header}>{header}</TableCell>)}</TableRow></TableHead><TableBody>{checks.data.checks.map((check: ReadinessCheck) => <TableRow key={check.check_code}><TableCell>{check.name}</TableCell><TableCell>{check.critical ? "Yes" : "Warning"}</TableCell><TableCell><Chip size="small" color={check.healthy ? "success" : "error"} label={check.status} /></TableCell><TableCell>{check.message}</TableCell></TableRow>)}</TableBody></Table></TableContainer></CardContent></Card>}</Box>;
}

export function DemoReadinessShowcasePage() {
  const qc = useQueryClient(); const showcase = useQuery({ queryKey: ["demo-readiness", "showcase"], queryFn: getDemoReadinessShowcase }); const profiles = useQuery({ queryKey: ["demo-readiness", "profiles"], queryFn: getDemoResetProfiles }); const [profile, setProfile] = useState("SOFT_RESET"); const business = getExperienceCode() === "business";
  const prepare = useMutation({ mutationFn: () => prepareDemoShowcase(true), onSuccess: () => { void qc.invalidateQueries({ queryKey: ["demo-readiness"] }); } }); const reset = useMutation({ mutationFn: () => resetDemoReadiness(profile, "Presenter reset the local EOS demo.", profile === "LOCAL_DEV_GENERATED_DATA_RESET" ? "RESET_LOCAL_DEMO_GENERATED_DATA" : undefined), onSuccess: () => { void qc.invalidateQueries({ queryKey: ["demo-readiness"] }); } }); const error = (showcase.error || profiles.error || prepare.error || reset.error) as Error | null;
  return <Box><Typography variant="overline" color="primary">Presenter preparation</Typography><Typography variant="h3" sx={{ fontWeight: 700, mb: 1 }}>Showcase Mode</Typography><Typography color="text.secondary" sx={{ mb: 3 }}>Prepare and replay local EOS storylines with explicit, reversible reset profiles.</Typography><SafetyBanner /><State loading={showcase.isLoading || profiles.isLoading} error={error} /><Alert severity="info" sx={{ mb: 3 }}>Showcase preparation verifies seeds and may create prepared scenario runs only when requested. It never calls a model or approves/executes an action.</Alert>{profiles.data && <Card sx={{ mb: 3 }}><CardContent><Typography variant="h5">Reset profiles</Typography><Stack direction={{ xs: "column", md: "row" }} gap={2} sx={{ mt: 2 }}><FormControl sx={{ minWidth: 300 }} disabled={business}><InputLabel id="reset-profile-label">Profile</InputLabel><Select labelId="reset-profile-label" label="Profile" value={profile} onChange={(event) => setProfile(event.target.value)}>{profiles.data.profiles.map((item) => <MenuItem value={item.profile} key={item.profile}>{item.profile}</MenuItem>)}</Select></FormControl>{!business && <><Button variant="outlined" color="warning" onClick={() => reset.mutate()} disabled={reset.isPending}>Reset local demo</Button><Button variant="contained" onClick={() => prepare.mutate()} disabled={prepare.isPending}>Prepare showcase</Button></>}</Stack><Typography variant="body2" color="text.secondary" sx={{ mt: 2 }}>Seed data and audit history are preserved. Local-dev generated-data reset requires an explicit confirmation string and still archives by marking records reset.</Typography></CardContent></Card>}{showcase.data && <><StatusBadges summary={showcase.data.readiness} /><Grid container spacing={2} sx={{ mb: 3 }}><Grid size={{ xs: 12, md: 5 }}><Card><CardContent><Typography variant="h5">Suggested presenter flow</Typography>{showcase.data.suggested_flow.map((step, index) => <Typography key={step} sx={{ mt: 1 }}>{index + 1}. {step}</Typography>)}</CardContent></Card></Grid><Grid size={{ xs: 12, md: 7 }}><Card><CardContent><Typography variant="h5" sx={{ mb: 2 }}>URL launcher</Typography><UrlList urls={showcase.data.urls} /></CardContent></Card></Grid></Grid></>}{(prepare.data || reset.data) && <Alert severity="success">Local showcase operation completed. Review the readiness score and open the guided scenario page.</Alert>}</Box>;
}

export function DemoReadinessGuidePage() { const guide = useQuery({ queryKey: ["demo-readiness", "guide"], queryFn: getDemoReadinessGuide }); return <Box><Typography variant="overline" color="primary">Browser-only validation</Typography><Typography variant="h3" sx={{ fontWeight: 700, mb: 1 }}>UI Test Guide</Typography><Typography color="text.secondary" sx={{ mb: 3 }}>{guide.data?.description || "Human-executable presenter checks."}</Typography><SafetyBanner /><State loading={guide.isLoading} error={guide.error as Error | null} />{guide.data?.sections.map((section) => <Card sx={{ mb: 2 }} key={section.title}><CardContent><Typography variant="h5">{section.title}</Typography>{section.steps.map((step) => <Paper key={`${section.title}-${step.step_number}`} sx={{ p: 1.5, mt: 1 }}><Typography fontWeight={700}>Step {step.step_number}: {step.what_to_click}</Typography><Typography variant="body2"><strong>Page:</strong> {step.page_url}</Typography><Typography variant="body2"><strong>Expected:</strong> {step.expected_result}</Typography><Typography variant="body2"><strong>Capture:</strong> {step.what_to_capture}</Typography><Typography variant="body2" color="text.secondary">{step.pass_fail_hint}</Typography></Paper>)}</CardContent></Card>)}</Box>; }

export function DemoReadinessSmokePage() { const report = useQuery({ queryKey: ["demo-readiness", "smoke"], queryFn: getDemoSmokeReport }); return <Box><Typography variant="overline" color="primary">Compact validation report</Typography><Typography variant="h3" sx={{ fontWeight: 700, mb: 1 }}>Smoke Report</Typography><Typography color="text.secondary" sx={{ mb: 3 }}>Read-only database and route perspective; no scenario, model, approval, or execution is triggered.</Typography><SafetyBanner /><State loading={report.isLoading} error={report.error as Error | null} />{report.data && <><StatusBadges summary={report.data.readiness} /><Grid container spacing={2} sx={{ mb: 3 }}>{[["Warehouses", report.data.seed_counts.warehouses], ["Scenarios", report.data.seed_counts.scenario_catalog], ["Scenario runs", report.data.scenario_counts.runs], ["Investigations", report.data.investigation_counts.cases], ["Action proposals", report.data.action_counts.proposals], ["Action executions", report.data.action_counts.executions]].map(([label, value]) => <Grid size={{ xs: 6, md: 2 }} key={String(label)}><Card><CardContent><Typography variant="body2" color="text.secondary">{label}</Typography><Typography variant="h5">{value}</Typography></CardContent></Card></Grid>)}</Grid><Card sx={{ mb: 3 }}><CardContent><Typography variant="h5">Stack URLs</Typography><UrlList urls={Object.entries(report.data.stack_urls).map(([label, url], index) => ({ label, url, experience: "stack", description: "Local EOS validation endpoint", recommended_order: index }))} /></CardContent></Card><Card><CardContent><Typography variant="h5">BFF exposure</Typography>{Object.entries(report.data.bff_exposure).map(([key, value]) => <Typography key={key} sx={{ mt: 1 }}>{key}: <strong>{value ? "available" : "not exposed"}</strong></Typography>)}</CardContent></Card></>}</Box>; }

export function DemoReadinessUrlsPage() { const urls = useQuery({ queryKey: ["demo-readiness", "urls"], queryFn: getDemoReadinessUrls }); return <Box><Typography variant="h3" sx={{ fontWeight: 700, mb: 2 }}>Presenter URL Launcher</Typography><State loading={urls.isLoading} error={urls.error as Error | null} />{urls.data && <UrlList urls={urls.data.urls} />}</Box>; }
