import { useNavigate, useParams, Link } from "react-router-dom";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Alert, Box, Button, Card, CardContent, Chip, CircularProgress, Grid, Paper, Stack, Table, TableBody, TableCell, TableContainer, TableHead, TableRow, Typography } from "@mui/material";
import { advanceDemoScenario, completeDemoScenarioStep, getDemoScenarioArtifacts, getDemoScenarioCatalog, getDemoScenarioNextAction, getDemoScenarioRun, getDemoScenarioRuns, getDemoScenarioSummary, resetDemoScenario, startDemoScenario, type DemoScenarioRun } from "../services/demoScenarioApi";

function State({ loading, error }: { loading: boolean; error: Error | null }) { if (loading) return <Box sx={{ display: "flex", gap: 1, alignItems: "center", mb: 2 }}><CircularProgress size={20} />Loading guided demo…</Box>; if (error) return <Alert severity="error" sx={{ mb: 2 }}>{error.message}</Alert>; return null; }
function SafeBanner() { return <Alert severity="warning" sx={{ mb: 3 }}>Guided scenarios use local synthetic EOS data only. No real model is called by default, no action is approved automatically, and no shell command, SQL, external send, ServiceNow update, or autonomous remediation is enabled.</Alert>; }

export function DemoScenarioCatalogPage() {
  const navigate = useNavigate();
  const summary = useQuery({ queryKey: ["demo-scenarios", "summary"], queryFn: getDemoScenarioSummary });
  const catalog = useQuery({ queryKey: ["demo-scenarios", "catalog"], queryFn: getDemoScenarioCatalog });
  const start = useMutation({ mutationFn: startDemoScenario, onSuccess: (run) => navigate(`/demo-scenarios/runs/${run.run_id}`) });
  return <Box><Typography variant="overline" color="primary">Presenter-guided EOS storylines</Typography><Typography variant="h3" sx={{ fontWeight: 700, mb: 1 }}>Demo Scenarios</Typography><Typography color="text.secondary" sx={{ mb: 3 }}>Run a complete, deterministic AMS investigation story without leaving the EOS experience.</Typography><SafeBanner /><State loading={summary.isLoading || catalog.isLoading} error={(summary.error || catalog.error) as Error | null} />{summary.data && <Stack direction="row" spacing={1} sx={{ mb: 3 }}><Chip label={`${summary.data.scenario_count} scenarios`} /><Chip label={`${summary.data.active_runs} active runs`} /><Chip color="success" variant="outlined" label="Local-only safe setup" /></Stack>}<Grid container spacing={2}>{(catalog.data || []).map((scenario) => <Grid size={{ xs: 12, md: 6 }} key={scenario.scenario_code}><Card sx={{ height: "100%" }}><CardContent><Typography variant="h5">{scenario.title}</Typography><Typography color="text.secondary" sx={{ my: 1 }}>{scenario.description}</Typography><Typography sx={{ mb: 1 }}><strong>Business value:</strong> {scenario.business_value}</Typography><Typography variant="body2">Experience: {scenario.default_experience} · {scenario.step_count} guided steps</Typography><Button variant="contained" sx={{ mt: 2 }} disabled={start.isPending} onClick={() => start.mutate(scenario.scenario_code)}>Start scenario</Button></CardContent></Card></Grid>)}</Grid>{start.error && <Alert severity="error" sx={{ mt: 2 }}>{start.error.message}</Alert>}</Box>;
}

export function DemoScenarioRunsPage() {
  const runs = useQuery({ queryKey: ["demo-scenarios", "runs"], queryFn: getDemoScenarioRuns });
  return <Box><Typography variant="overline" color="primary">Presenter workspace</Typography><Typography variant="h3" sx={{ fontWeight: 700, mb: 2 }}>Guided Scenario Runs</Typography><SafeBanner /><State loading={runs.isLoading} error={runs.error as Error | null} /><TableContainer component={Paper}><Table size="small"><TableHead><TableRow>{["Run", "Scenario", "Status", "Current step", "Started", "Open"].map((item) => <TableCell key={item}>{item}</TableCell>)}</TableRow></TableHead><TableBody>{(runs.data || []).map((run) => <TableRow key={run.run_id}><TableCell>{run.run_id}</TableCell><TableCell>{run.scenario_title}</TableCell><TableCell><Chip size="small" label={run.status} /></TableCell><TableCell>{run.current_step_code || "—"}</TableCell><TableCell>{new Date(run.started_at).toLocaleString()}</TableCell><TableCell><Button component={Link} to={`/demo-scenarios/runs/${run.run_id}`} size="small">Open run</Button></TableCell></TableRow>)}</TableBody></Table></TableContainer></Box>;
}

function PresenterPanel({ run, onAdvance, onComplete, onReset, busy }: { run: DemoScenarioRun; onAdvance: () => void; onComplete: () => void; onReset: () => void; busy: boolean }) { const step = run.steps.find((item) => item.status === "ACTIVE"); return <Card sx={{ mb: 2 }}><CardContent><Stack direction="row" justifyContent="space-between" alignItems="flex-start" gap={2}><Box><Typography variant="overline" color="primary">Current Step</Typography><Typography variant="h5">{step?.step_title || "Storyline complete"}</Typography><Typography sx={{ mt: 1 }}>{step?.presenter_instruction || run.outcome_summary}</Typography>{step && <Typography color="text.secondary" sx={{ mt: 1 }}><strong>What should appear:</strong> {step.expected_result}</Typography>}</Box><Chip color={run.status === "COMPLETED" ? "success" : "warning"} label={run.status} /></Stack>{step && <Stack direction="row" gap={1} flexWrap="wrap" sx={{ mt: 2 }}><Button variant="contained" onClick={onAdvance} disabled={busy}>Click Next</Button><Button variant="outlined" onClick={onComplete} disabled={busy}>Mark Complete</Button>{step.target_url && <Button component={Link} to={step.target_url} target="_blank">Open Target</Button>}</Stack>}<Button color="error" variant="text" sx={{ mt: 1 }} onClick={onReset} disabled={busy || run.status === "RESET"}>Reset run</Button></CardContent></Card>; }

export function DemoScenarioRunPage() {
  const { runId = "" } = useParams();
  const qc = useQueryClient();
  const run = useQuery({ queryKey: ["demo-scenarios", "run", runId], queryFn: () => getDemoScenarioRun(runId), enabled: Boolean(runId) });
  const artifacts = useQuery({ queryKey: ["demo-scenarios", "run", runId, "artifacts"], queryFn: () => getDemoScenarioArtifacts(runId), enabled: Boolean(runId) });
  const next = useQuery({ queryKey: ["demo-scenarios", "run", runId, "next"], queryFn: () => getDemoScenarioNextAction(runId), enabled: Boolean(runId) });
  const refresh = () => { void qc.invalidateQueries({ queryKey: ["demo-scenarios", "run", runId] }); void qc.invalidateQueries({ queryKey: ["demo-scenarios", "run", runId, "artifacts"] }); void qc.invalidateQueries({ queryKey: ["demo-scenarios", "run", runId, "next"] }); };
  const mutation = useMutation({ mutationFn: (kind: "advance" | "complete" | "reset") => kind === "advance" ? advanceDemoScenario(runId) : kind === "reset" ? resetDemoScenario(runId) : completeDemoScenarioStep(runId, run.data?.current_step_code || ""), onSuccess: refresh });
  return <Box><Button component={Link} to="/demo-scenarios" sx={{ mb: 2 }}>← Scenario catalog</Button><State loading={run.isLoading} error={run.error as Error | null} />{run.data && <><Typography variant="overline" color="primary">Guided Demo Run</Typography><Typography variant="h3" sx={{ fontWeight: 700 }}>{run.data.scenario_title}</Typography><Typography color="text.secondary" sx={{ mb: 2 }}>{run.data.run_id} · {run.data.scenario_code}</Typography><SafeBanner /><PresenterPanel run={run.data} busy={mutation.isPending} onAdvance={() => mutation.mutate("advance")} onComplete={() => mutation.mutate("complete")} onReset={() => mutation.mutate("reset")} />{next.data && <Alert severity="info" sx={{ mb: 2 }}><strong>Next action:</strong> {next.data.presenter_instruction} · {next.data.safe_boundary}</Alert>}<Grid container spacing={2}><Grid size={{ xs: 12, md: 7 }}><Card><CardContent><Typography variant="h5">Guided checklist</Typography>{run.data.steps.map((step) => <Paper key={step.step_code} sx={{ p: 1.5, my: 1 }}><Stack direction="row" justifyContent="space-between" gap={1}><Box><Typography fontWeight={700}>{step.step_order}. {step.step_title}</Typography><Typography variant="body2">{step.step_description}</Typography></Box><Chip size="small" label={step.status} /></Stack></Paper>)}</CardContent></Card></Grid><Grid size={{ xs: 12, md: 5 }}><Card><CardContent><Typography variant="h5">Generated artifacts</Typography>{(artifacts.data || run.data.artifacts).map((artifact) => <Paper key={artifact.id} sx={{ p: 1, my: 1 }}><Typography fontWeight={700}>{artifact.artifact_type}</Typography>{artifact.artifact_url ? <Button component={Link} to={artifact.artifact_url} size="small">{artifact.artifact_display}</Button> : <Typography>{artifact.artifact_display}</Typography>}</Paper>)}{!(artifacts.data || run.data.artifacts).length && <Typography color="text.secondary">No artifacts yet.</Typography>}</CardContent></Card><Card sx={{ mt: 2 }}><CardContent><Typography variant="h5">Scenario timeline</Typography>{run.data.timeline.map((event) => <Box key={event.id} sx={{ py: 1, borderBottom: 1, borderColor: "divider" }}><Typography fontWeight={700}>{event.event_title}</Typography><Typography variant="body2">{event.event_description}</Typography></Box>)}</CardContent></Card></Grid></Grid></>}{mutation.error && <Alert severity="error" sx={{ mt: 2 }}>{(mutation.error as Error).message}</Alert>}</Box>;
}
