import { useMutation, useQuery } from "@tanstack/react-query";
import { useState } from "react";
import { Alert, Box, Button, Card, CardContent, Chip, CircularProgress, Grid, Link as MuiLink, Paper, Stack, Table, TableBody, TableCell, TableContainer, TableHead, TableRow, Typography } from "@mui/material";
import { getStackHealth, getStackSummary, runStackTestAll, runStackTestLog, runStackTestMetric, runStackTestSpan, type StackHealthComponent, type TestAction, type TestAll } from "../services/observabilityStackApi";

function State({ loading, error }: { loading: boolean; error: Error | null }) { if (loading) return <Box sx={{ display: "flex", gap: 2, alignItems: "center", mb: 2 }}><CircularProgress size={22} /><Typography>Loading observability stack…</Typography></Box>; if (error) return <Alert severity="error" sx={{ mb: 2 }}>{error.message}</Alert>; return null; }
function Header({ title, description }: { title: string; description: string }) { return <><Typography variant="overline" color="primary">Local Observability Stack</Typography><Typography variant="h3" sx={{ mt: .5, mb: 1, fontWeight: 700 }}>{title}</Typography><Typography color="text.secondary" sx={{ mb: 4 }}>{description}</Typography></>; }
function Stat({ label, value }: { label: string; value: string | number | boolean }) { return <Card><CardContent><Typography color="text.secondary">{label}</Typography><Typography variant="h5" sx={{ mt: 1, fontWeight: 700 }}>{typeof value === "boolean" ? (value ? "Enabled" : "Disabled") : value}</Typography></CardContent></Card>; }
function statusChip(value: string) { return <Chip size="small" label={value} color={value === "healthy" || value === "RECORDED" || value === "EMITTED" ? "success" : value === "unknown" || value === "SKIPPED" ? "warning" : "error"} variant="outlined" />; }

export function ObservabilityStackOverviewPage() { const summary = useQuery({ queryKey: ["observability-stack", "summary"], queryFn: getStackSummary }); return <Box><Header title="Observability Stack" description="Local OpenTelemetry export to Tempo, Loki, Prometheus, and Grafana." /><Alert severity="info" sx={{ mb: 3 }}>Prompt 13 adds local external observability backends. Prompt 12 internal PostgreSQL runtime observability remains active.</Alert><State loading={summary.isLoading} error={summary.error as Error | null} />{summary.data && <><Grid container spacing={2} sx={{ mb: 4 }}>{[["OTel enabled", summary.data.otel_enabled], ["OTel available", summary.data.otel_available], ["Traces", summary.data.traces_enabled], ["Logs", summary.data.logs_enabled], ["Metrics", summary.data.metrics_enabled], ["Service", summary.data.service_name]].map(([label, value]) => <Grid key={String(label)} size={{ xs: 6, md: 2 }}><Stat label={String(label)} value={value as string | boolean} /></Grid>)}</Grid><Card><CardContent><Typography variant="h5" sx={{ mb: 2 }}>Configured endpoints</Typography><Stack spacing={1}><Typography>Collector: {summary.data.collector_endpoint}</Typography><Typography>Tempo: <MuiLink href={summary.data.tempo_url} target="_blank">{summary.data.tempo_url}</MuiLink></Typography><Typography>Loki: <MuiLink href={summary.data.loki_url} target="_blank">{summary.data.loki_url}</MuiLink></Typography><Typography>Prometheus: <MuiLink href={summary.data.prometheus_url} target="_blank">{summary.data.prometheus_url}</MuiLink></Typography><Typography>Grafana: <MuiLink href={summary.data.grafana_url} target="_blank">{summary.data.grafana_url}</MuiLink></Typography></Stack></CardContent></Card></>}</Box>; }

export function ObservabilityStackHealthPage() { const query = useQuery({ queryKey: ["observability-stack", "health"], queryFn: getStackHealth }); return <Box><Header title="Stack Health" description="Reachability checks for local observability services. Unknown means the backend could not reach the local endpoint." /><State loading={query.isLoading} error={query.error as Error | null} />{query.data && <><Alert severity={query.data.status === "healthy" ? "success" : "warning"} sx={{ mb: 3 }}>Overall stack status: {query.data.status}</Alert><TableContainer component={Paper}><Table><TableHead><TableRow><TableCell>Service</TableCell><TableCell>Status</TableCell><TableCell>URL</TableCell><TableCell>Detail</TableCell></TableRow></TableHead><TableBody>{query.data.components.map((row: StackHealthComponent) => <TableRow key={row.name}><TableCell>{row.name}</TableCell><TableCell>{statusChip(row.status)}</TableCell><TableCell>{row.url}</TableCell><TableCell>{row.detail || "—"}</TableCell></TableRow>)}</TableBody></Table></TableContainer></>}</Box>; }

export function ObservabilityStackTestPage() { const [result, setResult] = useState<TestAll | TestAction | null>(null); const [error, setError] = useState<string | null>(null); const run = (fn: () => Promise<TestAll | TestAction>) => { setError(null); void fn().then(setResult).catch((reason: Error) => setError(reason.message)); }; const mutation = useMutation({ mutationFn: runStackTestAll, onSuccess: (value) => { setError(null); setResult(value); } }); return <Box><Header title="Stack Test" description="Generate deterministic test telemetry through the OpenTelemetry SDK." /><Alert severity="info" sx={{ mb: 3 }}>These actions are local test signals. They do not change business data.</Alert><Stack direction={{ xs: "column", sm: "row" }} spacing={2}><Button variant="contained" onClick={() => run(runStackTestSpan)}>Generate Test Span</Button><Button variant="outlined" onClick={() => run(runStackTestLog)}>Generate Test Log</Button><Button variant="outlined" onClick={() => run(runStackTestMetric)}>Generate Test Metric</Button><Button variant="contained" color="secondary" onClick={() => mutation.mutate()} disabled={mutation.isPending}>Generate All</Button></Stack>{(result || error || mutation.error) && <Card sx={{ mt: 3 }}><CardContent>{(error || mutation.error) && <Alert severity="error">{error || (mutation.error as Error).message}</Alert>}{result && <pre style={{ whiteSpace: "pre-wrap" }}>{JSON.stringify(result, null, 2)}</pre>}</CardContent></Card>}</Box>; }

export function ObservabilityDashboardsPage() { const links = [{ label: "Grafana Home", url: "http://localhost:3001" }, { label: "EOS Runtime Observability Dashboard", url: "http://localhost:3001/d/eos-runtime-observability/eos-runtime-observability" }, { label: "EOS AMS Support Overview Dashboard", url: "http://localhost:3001/d/eos-ams-support-overview/eos-ams-support-overview" }, { label: "Prometheus", url: "http://localhost:9090" }, { label: "Tempo", url: "http://localhost:3200" }, { label: "Loki", url: "http://localhost:3100" }]; return <Box><Header title="Grafana Dashboards" description="Provisioned local dashboard and data-source links." /><Alert severity="info" sx={{ mb: 3 }}>Dashboards are provisioned into Grafana. If a dashboard has no panels yet, generate traffic from the Stack Test page first.</Alert><Grid container spacing={2}>{links.map(link => <Grid key={link.label} size={{ xs: 12, md: 6 }}><Card><CardContent><Typography variant="h6">{link.label}</Typography><MuiLink href={link.url} target="_blank" rel="noreferrer">{link.url}</MuiLink></CardContent></Card></Grid>)}</Grid></Box>; }
