import { useQuery, useMutation, useQueryClient } from "@tanstack/react-query";
import { Alert, Box, Button, Card, CardContent, Chip, CircularProgress, Grid, Link as MuiLink, Paper, Table, TableBody, TableCell, TableContainer, TableHead, TableRow, Typography } from "@mui/material";
import { Link, useParams } from "react-router-dom";
import type { ReactNode } from "react";
import { acknowledgeAlertEvent, createTicketFromAlertEvent, evaluateAlertRule, evaluateAlerts, getAlertEvent, getAlertEvents, getAlertRules, getAlertSummary, getEvaluationRuns, resolveAlertEvent, setAlertRuleEnabled, type AlertEvent } from "../services/observabilityAlertsApi";

const fmt = (value?: string | null) => value ? new Date(value).toLocaleString() : "—";
function Status({ value }: { value: string }) { return <Chip size="small" label={value} color={value === "OPEN" || value === "CRITICAL" ? "error" : value === "RESOLVED" ? "success" : "warning"} variant="outlined" />; }
function State({ loading, error }: { loading: boolean; error: Error | null }) { if (loading) return <Box sx={{ display: "flex", gap: 1, alignItems: "center", mb: 2 }}><CircularProgress size={20} /><Typography>Loading observability alerting…</Typography></Box>; if (error) return <Alert severity="error" sx={{ mb: 2 }}>{error.message}</Alert>; return null; }
function Header({ title, children }: { title: string; children?: ReactNode }) { return <Box sx={{ display: "flex", justifyContent: "space-between", alignItems: "center", mb: 3 }}><Box><Typography variant="overline" color="primary">Observability Alerting</Typography><Typography variant="h3" sx={{ fontWeight: 700 }}>{title}</Typography></Box>{children}</Box>; }

export function ObservabilityAlertsPage() { const queryClient = useQueryClient(); const summary = useQuery({ queryKey: ["obs-alerts", "summary"], queryFn: getAlertSummary }); const rules = useQuery({ queryKey: ["obs-alerts", "rules"], queryFn: getAlertRules }); const evaluate = useMutation({ mutationFn: evaluateAlerts, onSuccess: () => { void queryClient.invalidateQueries({ queryKey: ["obs-alerts"] }); } }); return <Box><Header title="Alert Overview"><Button variant="contained" onClick={() => evaluate.mutate()} disabled={evaluate.isPending}>Evaluate enabled rules</Button></Header><Alert severity="info" sx={{ mb: 3 }}>Rules evaluate local EOS signals and create auditable alert events. No remediation is executed; ticket creation is the only operational action.</Alert><State loading={summary.isLoading || rules.isLoading} error={(summary.error || rules.error) as Error | null} />{summary.data && <Grid container spacing={2} sx={{ mb: 4 }}>{[["Rules", summary.data.rules], ["Enabled", summary.data.enabled_rules], ["Open events", summary.data.open_events], ["Ticketed", summary.data.ticketed_events], ["Evaluations", summary.data.evaluation_runs], ["Tickets created", summary.data.tickets_created]].map(([label, value]) => <Grid size={{ xs: 6, md: 2 }} key={String(label)}><Card><CardContent><Typography color="text.secondary">{label}</Typography><Typography variant="h4">{value}</Typography></CardContent></Card></Grid>)}</Grid>}<Typography variant="h5" sx={{ mb: 2 }}>Recent rule catalog</Typography>{rules.data && <TableContainer component={Paper}><Table size="small"><TableHead><TableRow>{["Rule", "Signal", "Severity", "Enabled", "Target"].map((x) => <TableCell key={x}>{x}</TableCell>)}</TableRow></TableHead><TableBody>{rules.data.map((rule) => <TableRow key={rule.id}><TableCell><Link to="/observability-alerts/rules">{rule.rule_code}</Link><Typography variant="body2" color="text.secondary">{rule.name}</Typography></TableCell><TableCell>{rule.signal_type}{rule.metric_name ? ` / ${rule.metric_name}` : ""}</TableCell><TableCell><Status value={rule.severity} /></TableCell><TableCell>{rule.enabled ? "Yes" : "No"}</TableCell><TableCell>{rule.target_experience}</TableCell></TableRow>)}</TableBody></Table></TableContainer>}</Box>; }

export function ObservabilityAlertRulesPage() { const qc = useQueryClient(); const rules = useQuery({ queryKey: ["obs-alerts", "rules"], queryFn: getAlertRules }); const toggle = useMutation({ mutationFn: ({ id, enabled }: { id: string; enabled: boolean }) => setAlertRuleEnabled(id, enabled), onSuccess: () => void qc.invalidateQueries({ queryKey: ["obs-alerts", "rules"] }) }); const evaluate = useMutation({ mutationFn: evaluateAlertRule, onSuccess: () => void qc.invalidateQueries({ queryKey: ["obs-alerts"] }) }); return <Box><Header title="Alert Rules" /><State loading={rules.isLoading} error={rules.error as Error | null} /><TableContainer component={Paper}><Table><TableHead><TableRow>{["Rule", "Description", "Condition", "Severity", "Enabled", "Actions"].map((x) => <TableCell key={x}>{x}</TableCell>)}</TableRow></TableHead><TableBody>{rules.data?.map((rule) => <TableRow key={rule.id}><TableCell>{rule.rule_code}</TableCell><TableCell>{rule.description}</TableCell><TableCell>{rule.condition_operator} {rule.threshold_value ?? "—"}</TableCell><TableCell><Status value={rule.severity} /></TableCell><TableCell>{rule.enabled ? "Yes" : "No"}</TableCell><TableCell><Button size="small" onClick={() => evaluate.mutate(rule.id)}>Evaluate</Button><Button size="small" onClick={() => toggle.mutate({ id: rule.id, enabled: !rule.enabled })}>{rule.enabled ? "Disable" : "Enable"}</Button></TableCell></TableRow>)}</TableBody></Table></TableContainer></Box>; }

export function ObservabilityAlertEvaluationRunsPage() { const runs = useQuery({ queryKey: ["obs-alerts", "runs"], queryFn: getEvaluationRuns }); return <Box><Header title="Evaluation Runs" /><State loading={runs.isLoading} error={runs.error as Error | null} /><TableContainer component={Paper}><Table><TableHead><TableRow>{["Run", "Trigger", "Status", "Rules", "Created", "Suppressed", "Tickets", "Started"].map((x) => <TableCell key={x}>{x}</TableCell>)}</TableRow></TableHead><TableBody>{runs.data?.map((run) => <TableRow key={run.id}><TableCell>{run.run_id}</TableCell><TableCell>{run.trigger_source}</TableCell><TableCell><Status value={run.status} /></TableCell><TableCell>{run.rules_evaluated}</TableCell><TableCell>{run.events_created}</TableCell><TableCell>{run.events_suppressed}</TableCell><TableCell>{run.tickets_created}</TableCell><TableCell>{fmt(run.started_at)}</TableCell></TableRow>)}</TableBody></Table></TableContainer></Box>; }

function EventTable({ events }: { events: AlertEvent[] }) { return <TableContainer component={Paper}><Table size="small"><TableHead><TableRow>{["Event", "Rule", "Severity", "Status", "Observed", "Occurrences", "Ticket", "Last seen"].map((x) => <TableCell key={x}>{x}</TableCell>)}</TableRow></TableHead><TableBody>{events.map((event) => <TableRow key={event.id}><TableCell><Link to={`/observability-alerts/events/${event.id}`}>{event.event_id}</Link><Typography variant="body2">{event.title}</Typography></TableCell><TableCell>{event.rule_code}</TableCell><TableCell><Status value={event.severity} /></TableCell><TableCell><Status value={event.status} /></TableCell><TableCell>{event.observed_value ?? "—"}</TableCell><TableCell>{event.occurrence_count} / {event.suppressed_count} suppressed</TableCell><TableCell>{event.linked_ticket_number ? <MuiLink component={Link} to={`/ams/tickets/${event.created_ticket_id}`}>{event.linked_ticket_number}</MuiLink> : "—"}</TableCell><TableCell>{fmt(event.last_seen_at)}</TableCell></TableRow>)}</TableBody></Table></TableContainer>; }
export function ObservabilityAlertEventsPage() { const events = useQuery({ queryKey: ["obs-alerts", "events"], queryFn: getAlertEvents }); return <Box><Header title="Alert Events" /><State loading={events.isLoading} error={events.error as Error | null} />{events.data && <EventTable events={events.data} />}</Box>; }

export function ObservabilityAlertEventDetailPage() { const { eventId = "" } = useParams(); const qc = useQueryClient(); const event = useQuery({ queryKey: ["obs-alerts", "event", eventId], queryFn: () => getAlertEvent(eventId), enabled: Boolean(eventId) }); const action = useMutation<AlertEvent | { id: string; ticket_number: string }, Error, string>({ mutationFn: (kind: string) => kind === "ack" ? acknowledgeAlertEvent(eventId) : kind === "resolve" ? resolveAlertEvent(eventId) : createTicketFromAlertEvent(eventId), onSuccess: () => { void qc.invalidateQueries({ queryKey: ["obs-alerts"] }); void event.refetch(); } }); return <Box><Header title="Alert Event" /><State loading={event.isLoading} error={event.error as Error | null} />{event.data && <><Card sx={{ mb: 3 }}><CardContent><Typography variant="h5">{event.data.title}</Typography><Typography sx={{ mb: 1 }}>{event.data.description}</Typography><Status value={event.data.status} /> <Status value={event.data.severity} /><Typography sx={{ mt: 2 }}>Rule: {event.data.rule_code} · {event.data.condition_summary}</Typography><Typography>First seen: {fmt(event.data.first_seen_at)} · Last seen: {fmt(event.data.last_seen_at)}</Typography><Box sx={{ mt: 2, display: "flex", gap: 1 }}>{event.data.status === "OPEN" && <Button variant="outlined" onClick={() => action.mutate("ack")}>Acknowledge</Button>}{event.data.status !== "RESOLVED" && !event.data.created_ticket_id && <Button variant="contained" onClick={() => action.mutate("ticket")}>Create AMS ticket</Button>}{["OPEN", "ACKNOWLEDGED", "TICKETED"].includes(event.data.status) && <Button variant="outlined" onClick={() => action.mutate("resolve")}>Resolve</Button>}</Box>{event.data.created_ticket_id && <Typography sx={{ mt: 2 }}>Linked ticket: <MuiLink component={Link} to={`/ams/tickets/${event.data.created_ticket_id}`}>{event.data.linked_ticket_number || event.data.created_ticket_id}</MuiLink></Typography>}</CardContent></Card><Typography variant="h5" sx={{ mb: 2 }}>Evidence</Typography><TableContainer component={Paper}><Table><TableHead><TableRow><TableCell>Type</TableCell><TableCell>Title</TableCell><TableCell>Summary</TableCell><TableCell>Source</TableCell></TableRow></TableHead><TableBody>{event.data.evidence.map((item) => <TableRow key={item.id}><TableCell>{item.evidence_type}</TableCell><TableCell>{item.title}</TableCell><TableCell>{item.summary}</TableCell><TableCell>{item.source_url || "Internal EOS"}</TableCell></TableRow>)}</TableBody></Table></TableContainer></>}</Box>; }
