import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Link, useParams } from "react-router-dom";
import { Alert, Box, Button, Card, CardContent, Chip, CircularProgress, Grid, Paper, Stack, Table, TableBody, TableCell, TableContainer, TableHead, TableRow, Typography } from "@mui/material";
import { getRuntimeSummary, getRuntimeTraceDetail, getRuntimeTraces, runBackendHealthProbe, type RuntimeLog, type RuntimeMetric, type RuntimeSpan } from "../services/runtimeObservabilityApi";

const chip = (value: string) => <Chip size="small" label={value.replaceAll("_", " ")} color={value === "ERROR" || value === "HIGH" ? "error" : value === "DEGRADED" || value === "SLOW" || value === "MEDIUM" ? "warning" : value === "SUCCESS" || value === "OK" ? "success" : "default"} variant="outlined" />;
function State({ loading, error }: { loading: boolean; error: Error | null }) { if (loading) return <Box sx={{ display: "flex", gap: 2, alignItems: "center", mb: 2 }}><CircularProgress size={22} /><Typography>Loading runtime telemetry…</Typography></Box>; if (error) return <Alert severity="error" sx={{ mb: 2 }}>{error.message}</Alert>; return null; }
function Header({ title, description }: { title: string; description: string }) { return <><Typography variant="overline" color="primary">Runtime Observability</Typography><Typography variant="h3" sx={{ mt: .5, mb: 1, fontWeight: 700 }}>{title}</Typography><Typography color="text.secondary" sx={{ mb: 4 }}>{description}</Typography></>; }
function SummaryCard({ label, value }: { label: string; value: number | string }) { return <Card><CardContent><Typography color="text.secondary">{label}</Typography><Typography variant="h4" sx={{ mt: 1, fontWeight: 700 }}>{typeof value === "number" ? value.toLocaleString() : value}</Typography></CardContent></Card>; }
function TraceTable({ rows }: { rows: Awaited<ReturnType<typeof getRuntimeTraces>> }) { return <TableContainer component={Paper}><Table size="small"><TableHead><TableRow>{["Trace", "Name", "Status", "Route/root reference", "Duration", "Started", "Summary"].map(h => <TableCell key={h}>{h}</TableCell>)}</TableRow></TableHead><TableBody>{rows.map(row => <TableRow key={row.id}><TableCell><Button component={Link} size="small" to={`/observability/runtime/traces/${row.trace_id}`}>{row.trace_id}</Button></TableCell><TableCell>{row.trace_name}</TableCell><TableCell>{chip(row.status)}</TableCell><TableCell>{row.root_reference || "—"}</TableCell><TableCell>{row.duration_ms ?? "—"} ms</TableCell><TableCell>{new Date(row.started_at).toLocaleString()}</TableCell><TableCell>{row.summary}</TableCell></TableRow>)}</TableBody></Table></TableContainer>; }

export function RuntimeObservabilityOverviewPage() { const q = useQueryClient(); const summary = useQuery({ queryKey: ["runtime-observability", "summary"], queryFn: getRuntimeSummary }); const traces = useQuery({ queryKey: ["runtime-observability", "traces"], queryFn: getRuntimeTraces }); const probe = useMutation({ mutationFn: runBackendHealthProbe, onSuccess: () => { void q.invalidateQueries({ queryKey: ["runtime-observability"] }); } }); return <Box><Header title="Runtime Observability" description="Live EOS backend request telemetry persisted into the application observability tables." /><Alert severity="info" sx={{ mb: 3 }}>Runtime observability captures live EOS backend request traces, spans, logs, and metrics. External observability backends are not enabled yet.</Alert><Button variant="contained" onClick={() => probe.mutate()} disabled={probe.isPending}>Run Backend Health Probe</Button>{probe.data && <Alert severity={probe.data.status === "SUCCESS" ? "success" : "warning"} sx={{ mt: 2 }}>Probe {probe.data.status}: <Button component={Link} size="small" to={`/observability/runtime/traces/${probe.data.trace_identifier}`}>{probe.data.trace_identifier}</Button> · database {probe.data.database_status} · Redis {probe.data.redis_status}</Alert>}{probe.error && <Alert severity="error" sx={{ mt: 2 }}>{(probe.error as Error).message}</Alert>}<State loading={summary.isLoading || traces.isLoading} error={(summary.error || traces.error) as Error | null} />{summary.data && <Grid container spacing={2} sx={{ mt: 1, mb: 4 }}>{[["Runtime traces", summary.data.runtime_traces], ["Successful requests", summary.data.successful_requests], ["Degraded requests", summary.data.degraded_requests], ["Error requests", summary.data.error_requests], ["Average latency (ms)", summary.data.average_latency_ms], ["Max latency (ms)", summary.data.max_latency_ms], ["Runtime logs", summary.data.runtime_logs], ["Runtime metric samples", summary.data.runtime_metric_samples]].map(([label, value]) => <Grid key={String(label)} size={{ xs: 6, md: 3 }}><SummaryCard label={String(label)} value={value as number} /></Grid>)}</Grid>}{traces.data && <><Typography variant="h5" sx={{ mb: 1 }}>Recent runtime traces</Typography><TraceTable rows={traces.data.slice(0, 20)} /></>}</Box>; }

export function RuntimeTracesPage() { const query = useQuery({ queryKey: ["runtime-observability", "traces"], queryFn: getRuntimeTraces }); return <Box><Header title="Runtime Traces" description="Captured backend API request traces with correlation metadata available in trace detail." /><State loading={query.isLoading} error={query.error as Error | null} />{query.data && <TraceTable rows={query.data} />}</Box>; }

export function RuntimeTraceDetailPage() { const { traceId = "" } = useParams(); const query = useQuery({ queryKey: ["runtime-observability", "trace", traceId], queryFn: () => getRuntimeTraceDetail(traceId), enabled: Boolean(traceId) }); return <Box><Button component={Link} to="/observability/runtime/traces" sx={{ mb: 2 }}>← Back to runtime traces</Button><State loading={query.isLoading} error={query.error as Error | null} />{query.data && <><Header title={query.data.trace_id} description={query.data.trace_name} /><Stack direction="row" spacing={1} sx={{ mb: 3 }}>{chip(query.data.status)}<Chip size="small" label={`${query.data.duration_ms ?? "—"} ms`} /><Typography color="text.secondary">Request: {query.data.request_id || "—"} · Correlation: {query.data.correlation_id || "—"}</Typography></Stack><Card sx={{ mb: 3 }}><CardContent><Typography>{query.data.summary}</Typography><Typography color="text.secondary" sx={{ mt: 1 }}>Route: {query.data.root_reference || "—"} · Traceparent: {query.data.traceparent || "—"}</Typography></CardContent></Card><Typography variant="h5" sx={{ mb: 1 }}>Spans</Typography><TableContainer component={Paper} sx={{ mb: 3 }}><Table size="small"><TableHead><TableRow>{["Span", "Operation", "Status", "Duration", "Error"].map(h => <TableCell key={h}>{h}</TableCell>)}</TableRow></TableHead><TableBody>{query.data.spans.map((row: RuntimeSpan) => <TableRow key={row.id}><TableCell>{row.span_name}</TableCell><TableCell>{row.operation_type}</TableCell><TableCell>{chip(row.status)}</TableCell><TableCell>{row.duration_ms ?? "—"} ms</TableCell><TableCell>{row.error_message || "—"}</TableCell></TableRow>)}</TableBody></Table></TableContainer><Typography variant="h5" sx={{ mb: 1 }}>Logs</Typography><TableContainer component={Paper} sx={{ mb: 3 }}><Table size="small"><TableHead><TableRow>{["Time", "Level", "Event", "Message"].map(h => <TableCell key={h}>{h}</TableCell>)}</TableRow></TableHead><TableBody>{query.data.logs.map((row: RuntimeLog) => <TableRow key={row.id}><TableCell>{new Date(row.logged_at).toLocaleTimeString()}</TableCell><TableCell>{chip(row.level)}</TableCell><TableCell>{row.event_type}</TableCell><TableCell>{row.message}</TableCell></TableRow>)}</TableBody></Table></TableContainer><Typography variant="h5" sx={{ mb: 1 }}>Metric samples</Typography><TableContainer component={Paper}><Table size="small"><TableHead><TableRow>{["Time", "Metric", "Value", "Unit", "Severity"].map(h => <TableCell key={h}>{h}</TableCell>)}</TableRow></TableHead><TableBody>{query.data.metrics.map((row: RuntimeMetric) => <TableRow key={row.id}><TableCell>{new Date(row.recorded_at).toLocaleTimeString()}</TableCell><TableCell>{row.metric_name}</TableCell><TableCell>{row.metric_value}</TableCell><TableCell>{row.metric_unit}</TableCell><TableCell>{row.severity ? chip(row.severity) : "—"}</TableCell></TableRow>)}</TableBody></Table></TableContainer></>}</Box>; }
